import { profileFromSeed, type FaultFamily } from "./families";

type Row = [string, string, string, string, string, string, FaultFamily, number, string[]];

const AEGW = ["L7FEC41S"];
const AEGD = ["FEE83710PM"];
const ELW = ["EW6S226S"];
const ELD = ["ESF7765ROX"];
const WPW = ["WFW5620HW"];
const WPD = ["WDTA50SAHZ"];
const BKW = ["WTG941B3"];
const BKD = ["DIN28431"];
const CDW = ["RO14164DWMCE"];
const CDD = ["CDPN 2D622PX"];
const HPW = ["NSWM1045C"];
const HPD = ["HFC 3C26 CW"];

const rows: Row[] = [
  ["AEG", "aeg", "Washer", "washer", "E11", "Water inlet / fill timeout.", "fill", 70, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E20", "Drain problem.", "drain", 74, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E21", "Drain pump / timeout.", "drain", 68, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E31", "NTC / temperature sensor.", "thermistor", 52, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E32", "NTC variant.", "thermistor", 48, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E41", "Door lock.", "door", 66, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E43", "Door lock / board communication.", "door", 54, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E51", "Motor / tachometer.", "motor", 50, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E52", "Motor control.", "motor", 46, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E61", "Heating timeout.", "heat", 50, AEGW],
  ["AEG", "aeg", "Washer", "washer", "E62", "Heating overheat / NTC.", "heat", 46, AEGW],
  ["AEG", "aeg", "Washer", "washer", "C1", "Water inlet (C display family).", "fill", 58, AEGW],
  ["AEG", "aeg", "Washer", "washer", "C2", "Drain (C display family).", "drain", 56, AEGW],
  ["AEG", "aeg", "Washer", "washer", "C3", "Unbalance / spin.", "unbalance", 54, AEGW],
  ["AEG", "aeg", "Washer", "washer", "C9", "Overflow / leak path.", "overflow", 44, AEGW],
  ["AEG", "aeg", "Dishwasher", "dishwasher", "i10", "Water inlet.", "fill", 62, AEGD],
  ["AEG", "aeg", "Dishwasher", "dishwasher", "i20", "Drain.", "dw_drain", 64, AEGD],
  ["AEG", "aeg", "Dishwasher", "dishwasher", "i30", "Heating / NTC.", "dw_heat", 52, AEGD],
  ["AEG", "aeg", "Dishwasher", "dishwasher", "i40", "AquaStop / leak in base.", "aquastop", 70, AEGD],
  ["AEG", "aeg", "Dryer", "dryer", "E51", "Motor / drum.", "motor", 40, ["T8DEC846S"]],
  ["AEG", "aeg", "Dryer", "dryer", "E53", "NTC / temperature.", "dryer_heat", 42, ["T8DEC846S"]],
  ["AEG", "aeg", "Dryer", "dryer", "E61", "Heating circuit.", "dryer_heat", 44, ["T8DEC846S"]],
  ["Electrolux", "electrolux", "Washer", "washer", "E11", "Water inlet.", "fill", 68, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E20", "Drain.", "drain", 72, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E21", "Drain pump.", "drain", 64, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E31", "NTC.", "thermistor", 50, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E41", "Door lock.", "door", 64, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E51", "Motor.", "motor", 48, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E61", "Heater.", "heat", 48, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E62", "Overheat / NTC.", "heat", 44, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E13", "Leak / AquaProtect.", "leak", 56, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E23", "Drain filter / pump.", "drain", 52, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E35", "Overflow.", "overflow", 50, ELW],
  ["Electrolux", "electrolux", "Washer", "washer", "E40", "Door.", "door", 54, ELW],
  ["Electrolux", "electrolux", "Dishwasher", "dishwasher", "i10", "Water inlet.", "fill", 60, ELD],
  ["Electrolux", "electrolux", "Dishwasher", "dishwasher", "i20", "Drain.", "dw_drain", 62, ELD],
  ["Electrolux", "electrolux", "Dishwasher", "dishwasher", "i30", "Heating.", "dw_heat", 50, ELD],
  ["Electrolux", "electrolux", "Dishwasher", "dishwasher", "i50", "AquaStop.", "aquastop", 66, ELD],
  ["Electrolux", "electrolux", "Dryer", "dryer", "E51", "Motor.", "motor", 40, ["EW8H258S"]],
  ["Electrolux", "electrolux", "Dryer", "dryer", "E53", "NTC.", "dryer_heat", 42, ["EW8H258S"]],
  ["Electrolux", "electrolux", "Dryer", "dryer", "E61", "Heater.", "dryer_heat", 44, ["EW8H258S"]],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F01", "NTC / temperature.", "thermistor", 56, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F02", "Drain timeout.", "drain", 72, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F03", "NTC variant.", "thermistor", 50, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F05", "Water inlet / flow.", "fill", 64, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F06", "Drive / tachometer.", "motor", 52, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F07", "Motor / inverter.", "motor", 50, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F08", "Heater / overflow related.", "heat", 48, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F09", "Overflow / pressure.", "overflow", 50, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F11", "Drain pump.", "drain", 66, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F12", "Motor control.", "motor", 46, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F13", "Dispenser / flow.", "fill", 42, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F21", "Drain.", "drain", 58, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F22", "Door lock.", "door", 60, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F24", "Overflow.", "overflow", 48, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "F26", "Door lock.", "door", 52, WPW],
  ["Whirlpool", "whirlpool", "Washer", "washer", "SUDS", "Excess suds — not a failed pump.", "suds", 62, WPW],
  ["Whirlpool", "whirlpool", "Dishwasher", "dishwasher", "F1E", "NTC / temperature.", "thermistor", 48, WPD],
  ["Whirlpool", "whirlpool", "Dishwasher", "dishwasher", "F2E", "Stuck key / panel.", "power", 36, WPD],
  ["Whirlpool", "whirlpool", "Dishwasher", "dishwasher", "F6E", "Fill / flow meter.", "fill", 58, WPD],
  ["Whirlpool", "whirlpool", "Dishwasher", "dishwasher", "F7E", "Heating / NTC.", "dw_heat", 50, WPD],
  ["Whirlpool", "whirlpool", "Dishwasher", "dishwasher", "F8E", "Drain / overflow.", "dw_drain", 56, WPD],
  ["Whirlpool", "whirlpool", "Dishwasher", "dishwasher", "F9E", "Fill valve.", "fill", 52, WPD],
  ["Beko", "beko", "Washer", "washer", "E01", "Door lock.", "door", 68, BKW],
  ["Beko", "beko", "Washer", "washer", "E02", "NTC / temperature.", "thermistor", 52, BKW],
  ["Beko", "beko", "Washer", "washer", "E03", "Heater.", "heat", 50, BKW],
  ["Beko", "beko", "Washer", "washer", "E04", "NTC variant.", "thermistor", 44, BKW],
  ["Beko", "beko", "Washer", "washer", "E05", "NTC / heater circuit.", "heat", 46, BKW],
  ["Beko", "beko", "Washer", "washer", "E07", "Motor / tachometer.", "motor", 50, BKW],
  ["Beko", "beko", "Washer", "washer", "E08", "Overflow / pressure.", "overflow", 54, BKW],
  ["Beko", "beko", "Washer", "washer", "E09", "Water inlet valve.", "fill", 62, BKW],
  ["Beko", "beko", "Washer", "washer", "E10", "Heater / NTC.", "heat", 46, BKW],
  ["Beko", "beko", "Washer", "washer", "E11", "Drain pump.", "drain", 66, BKW],
  ["Beko", "beko", "Washer", "washer", "E13", "NTC.", "thermistor", 40, BKW],
  ["Beko", "beko", "Washer", "washer", "E17", "Overflow.", "overflow", 48, BKW],
  ["Beko", "beko", "Washer", "washer", "E18", "Water inlet timeout.", "fill", 58, BKW],
  ["Beko", "beko", "Dishwasher", "dishwasher", "E01", "Door.", "door", 56, BKD],
  ["Beko", "beko", "Dishwasher", "dishwasher", "E02", "NTC.", "thermistor", 48, BKD],
  ["Beko", "beko", "Dishwasher", "dishwasher", "E03", "Heater.", "dw_heat", 50, BKD],
  ["Beko", "beko", "Dishwasher", "dishwasher", "E05", "NTC / fill.", "fill", 46, BKD],
  ["Beko", "beko", "Dishwasher", "dishwasher", "E08", "Overflow.", "overflow", 48, BKD],
  ["Beko", "beko", "Dishwasher", "dishwasher", "E14", "Drain.", "dw_drain", 58, BKD],
  ["Candy", "candy", "Washer", "washer", "E01", "Door lock.", "door", 64, CDW],
  ["Candy", "candy", "Washer", "washer", "E02", "Drain.", "drain", 68, CDW],
  ["Candy", "candy", "Washer", "washer", "E03", "NTC / temperature.", "thermistor", 50, CDW],
  ["Candy", "candy", "Washer", "washer", "E04", "Heater.", "heat", 48, CDW],
  ["Candy", "candy", "Washer", "washer", "E05", "Water inlet.", "fill", 62, CDW],
  ["Candy", "candy", "Washer", "washer", "E07", "Motor / tachometer.", "motor", 50, CDW],
  ["Candy", "candy", "Washer", "washer", "E09", "Pressure / level sensor.", "level_sensor", 46, CDW],
  ["Candy", "candy", "Washer", "washer", "E11", "Drain pump.", "drain", 56, CDW],
  ["Candy", "candy", "Washer", "washer", "E13", "NTC.", "thermistor", 40, CDW],
  ["Candy", "candy", "Washer", "washer", "E16", "Heater circuit.", "heat", 42, CDW],
  ["Candy", "candy", "Washer", "washer", "E17", "Overheat.", "heat", 40, CDW],
  ["Candy", "candy", "Washer", "washer", "E21", "Motor.", "motor", 44, CDW],
  ["Candy", "candy", "Dishwasher", "dishwasher", "E1", "Water inlet.", "fill", 54, CDD],
  ["Candy", "candy", "Dishwasher", "dishwasher", "E2", "Drain.", "dw_drain", 56, CDD],
  ["Candy", "candy", "Dishwasher", "dishwasher", "E3", "NTC / heat.", "dw_heat", 48, CDD],
  ["Candy", "candy", "Dishwasher", "dishwasher", "E4", "NTC.", "thermistor", 44, CDD],
  ["Candy", "candy", "Dishwasher", "dishwasher", "E5", "Fill timeout.", "fill", 50, CDD],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F01", "NTC.", "thermistor", 54, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F02", "Motor.", "motor", 56, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F03", "NTC variant.", "thermistor", 48, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F04", "Pressure sensor.", "level_sensor", 50, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F05", "Pressure / drain related.", "drain", 60, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F06", "NTC / heater.", "heat", 46, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F07", "Motor / inverter.", "motor", 48, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F08", "Heater.", "heat", 50, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F09", "Pressure / overflow.", "overflow", 48, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F11", "Drain pump.", "drain", 62, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F12", "Motor control.", "motor", 44, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F13", "Dispenser.", "fill", 40, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F15", "Heater / NTC.", "heat", 42, HPW],
  ["Hotpoint", "hotpoint", "Washer", "washer", "F18", "Flow meter / fill.", "fill", 52, HPW],
  ["Hotpoint", "hotpoint", "Dishwasher", "dishwasher", "F01", "NTC.", "thermistor", 46, HPD],
  ["Hotpoint", "hotpoint", "Dishwasher", "dishwasher", "F04", "Pressure / fill.", "fill", 50, HPD],
  ["Hotpoint", "hotpoint", "Dishwasher", "dishwasher", "F06", "NTC / heat.", "dw_heat", 48, HPD],
  ["Hotpoint", "hotpoint", "Dishwasher", "dishwasher", "F08", "Heater.", "dw_heat", 50, HPD],
  ["Hotpoint", "hotpoint", "Dishwasher", "dishwasher", "F12", "Fill / flow.", "fill", 48, HPD],
  ["Hotpoint", "hotpoint", "Dishwasher", "dishwasher", "F15", "Drain.", "dw_drain", 54, HPD],
];

export const BATCH4_ERRORS = rows.map((row) =>
  profileFromSeed({
    brand: row[0],
    brand_slug: row[1],
    appliance: row[2],
    appliance_slug: row[3],
    code: row[4],
    meaning: row[5],
    family: row[6],
    demand: row[7],
    models: row[8],
  }),
);
