import { profileFromSeed, type FaultFamily } from "./families";

const SW = ["WW80T554DAN", "WW90T986ASH", "WF45R6100AW"];
const LW = ["F4V310WNE", "WM4000HWA"];
const BW = ["WAN282X1GB", "WAU28PH9GB"];
const BD = ["SMS6ZCI49T", "SHPM88Z75N", "SMV4HVX38G"];
const SD = ["DW80R5061US", "DW60M5070FS"];
const SDry = ["DVE45R6100W", "DV90T5240AT"];
const LDry = ["DLE3600W", "RC90V9AV2W"];
const SF = ["RF28R7351SR", "RB38T605DB1"];
const MW = ["WWD120", "WCR870"];
const MD = ["G7160SCVI", "G7360C"];
const SO = ["NV51K6650SS", "NQ5B4553FB"];

const rows: Array<[string, string, string, string, string, string, FaultFamily, number, string[]]> = [
  ["Samsung", "samsung", "Washer", "washer", "1C", "Water level sensor error.", "level_sensor", 64, SW],
  ["Samsung", "samsung", "Washer", "washer", "1E", "Water level sensor error (1E family).", "level_sensor", 58, SW],
  ["Samsung", "samsung", "Washer", "washer", "3C", "Motor error (3C family).", "motor", 62, SW],
  ["Samsung", "samsung", "Washer", "washer", "3E", "Motor / hall sensor error (3E family).", "motor", 60, SW],
  ["Samsung", "samsung", "Washer", "washer", "5C", "Drain error (5C family).", "drain", 70, SW],
  ["Samsung", "samsung", "Washer", "washer", "3C1", "Motor drive error, variant 3C1.", "motor", 42, SW],
  ["Samsung", "samsung", "Washer", "washer", "3C3", "Motor drive error, variant 3C3.", "motor", 40, SW],
  ["Samsung", "samsung", "Washer", "washer", "6C", "Power / PCB communication related fault on some WW models — treat as power/comms, not a DIY board swap.", "power", 36, SW],
  ["Samsung", "samsung", "Washer", "washer", "8C", "MEMS / vibration sensor error on some models.", "unbalance", 38, SW],
  ["Samsung", "samsung", "Washer", "washer", "8E", "MEMS / unbalance sensor family.", "unbalance", 34, SW],
  ["Samsung", "samsung", "Washer", "washer", "9C", "Low voltage / power error.", "power", 44, SW],
  ["Samsung", "samsung", "Washer", "washer", "11E", "Communication error between display and main board.", "power", 40, SW],
  ["Samsung", "samsung", "Washer", "washer", "12E", "Button / panel communication error.", "power", 32, SW],
  ["Samsung", "samsung", "Washer", "washer", "Ub", "Unbalanced load (Ub display).", "unbalance", 72, SW],
  ["Samsung", "samsung", "Washer", "washer", "UC", "Unbalanced load (UC display).", "unbalance", 48, SW],
  ["Samsung", "samsung", "Washer", "washer", "dC", "Unbalanced load on some models (dC vs DC door — confirm the exact glyphs).", "unbalance", 55, SW],
  ["Samsung", "samsung", "Washer", "washer", "DC1", "Door lock error, variant DC1.", "door", 46, SW],
  ["Samsung", "samsung", "Washer", "washer", "LC", "Leak detected (LC family).", "leak", 52, SW],
  ["Samsung", "samsung", "Washer", "washer", "HE", "Water temperature issue (official table groups H1/HC/HE).", "heat", 50, SW],
  ["Samsung", "samsung", "Washer", "washer", "HC", "Water temperature issue (official table groups H1/HC/HE).", "heat", 42, SW],
  ["Samsung", "samsung", "Washer", "washer", "Sud", "Too many suds detected.", "suds", 70, SW],
  ["Samsung", "samsung", "Washer", "washer", "SUd", "Suds detected (alternate glyph).", "suds", 44, SW],
  ["Samsung", "samsung", "Washer", "washer", "PF", "Power failure / interruption during a cycle.", "power", 48, SW],
  ["Samsung", "samsung", "Washer", "washer", "4C2", "Water supply error, hot or second inlet path on some models.", "fill", 40, SW],
  ["Samsung", "samsung", "Washer", "washer", "5C2", "Draining error, variant 5C2.", "drain", 38, SW],
  ["Samsung", "samsung", "Washer", "washer", "BE", "Motor / speed sensor family (bE/BE).", "motor", 36, SW],
  ["Samsung", "samsung", "Washer", "washer", "AE", "Communication / leak-related AE on some washers — confirm on the sticker. We treat the safe user checks first.", "leak", 34, SW],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "4E", "Water supply error.", "fill", 68, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "4C", "Water supply error (4C dishwasher).", "fill", 62, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "5E", "Drain error.", "dw_drain", 74, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "OE", "Overflow / leak related on some DW models.", "overflow", 50, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "LE", "Leak detected.", "aquastop", 56, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "HE", "Heater error.", "dw_heat", 52, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "tE", "Temperature sensor error.", "thermistor", 46, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "3E", "Circulation / motor related error.", "motor", 40, SD],
  ["Samsung", "samsung", "Dryer", "dryer", "tE", "Temperature sensor error.", "dryer_heat", 58, SDry],
  ["Samsung", "samsung", "Dryer", "dryer", "HE", "Heater error.", "dryer_heat", 60, SDry],
  ["Samsung", "samsung", "Dryer", "dryer", "dE", "Door error.", "door", 50, SDry],
  ["Samsung", "samsung", "Dryer", "dryer", "dC", "Door / control variant on some dryers.", "door", 42, SDry],
  ["Samsung", "samsung", "Dryer", "dryer", "3C", "Motor error.", "motor", 44, SDry],
  ["Samsung", "samsung", "Fridge", "fridge", "22E", "Defrost sensor / defrost circuit error on some French-door models — model-specific.", "fridge_sensor", 40, SF],
  ["Samsung", "samsung", "Fridge", "fridge", "88", "Display 88 / 8E family often points to a sensor or defrost issue — confirm on the exact model.", "fridge_sensor", 48, SF],
  ["Samsung", "samsung", "Fridge", "fridge", "OF", "Off / freezer-off display is not always a fault. If unexpected, treat as control/sensor.", "fridge_sensor", 36, SF],
  ["Samsung", "samsung", "Oven", "oven", "tE", "Oven temperature sensor error.", "oven_heat", 50, SO],
  ["Samsung", "samsung", "Oven", "oven", "SE", "Safety / key-lock related on some models; also used for steam errors — follow the exact glyph.", "oven_heat", 38, SO],
  ["Samsung", "samsung", "Oven", "oven", "dC", "Door lock / latch error on some ovens.", "door", 40, SO],
  ["LG", "lg", "Washer", "washer", "FE", "Overflow / too much water.", "overflow", 64, LW],
  ["LG", "lg", "Washer", "washer", "tE", "Thermistor error.", "thermistor", 58, LW],
  ["LG", "lg", "Washer", "washer", "PE", "Water level sensor (pressure) error.", "level_sensor", 62, LW],
  ["LG", "lg", "Washer", "washer", "LE", "Motor locked / overload.", "motor", 66, LW],
  ["LG", "lg", "Washer", "washer", "CE", "Overload / current error.", "motor", 50, LW],
  ["LG", "lg", "Washer", "washer", "PF", "Power failure.", "power", 54, LW],
  ["LG", "lg", "Washer", "washer", "AE", "Leak / Aqua Stop related on some models.", "leak", 48, LW],
  ["LG", "lg", "Washer", "washer", "dE", "Door error (dE family).", "door", 52, LW],
  ["LG", "lg", "Washer", "washer", "OE1", "Drain error, variant.", "drain", 40, LW],
  ["LG", "lg", "Washer", "washer", "IE1", "Inlet error, variant.", "fill", 38, LW],
  ["LG", "lg", "Dishwasher", "dishwasher", "OE", "Drain error.", "dw_drain", 72, ["LDF5545ST", "DF455HSS"]],
  ["LG", "lg", "Dishwasher", "dishwasher", "IE", "Water inlet error.", "fill", 64, ["LDF5545ST"]],
  ["LG", "lg", "Dishwasher", "dishwasher", "AE", "Leak detected.", "aquastop", 58, ["LDF5545ST"]],
  ["LG", "lg", "Dishwasher", "dishwasher", "HE", "Heater error.", "dw_heat", 52, ["LDF5545ST"]],
  ["LG", "lg", "Dishwasher", "dishwasher", "tE", "Thermistor error.", "thermistor", 46, ["LDF5545ST"]],
  ["LG", "lg", "Dishwasher", "dishwasher", "FE", "Overflow.", "overflow", 44, ["LDF5545ST"]],
  ["LG", "lg", "Dishwasher", "dishwasher", "LE", "Motor / wash motor related.", "motor", 42, ["LDF5545ST"]],
  ["LG", "lg", "Dryer", "dryer", "d90", "Restricted airflow (d90 family).", "dryer_air", 52, LDry],
  ["LG", "lg", "Dryer", "dryer", "tE", "Thermistor error.", "dryer_heat", 48, LDry],
  ["LG", "lg", "Dryer", "dryer", "dE", "Door error.", "door", 44, LDry],
  ["LG", "lg", "Fridge", "fridge", "F", "Some LG fridges show F with a number for sensor faults — this row covers F-series sensor checks, not a sealed-system guess.", "fridge_sensor", 42, ["LTCS20020S", "GSX960NSAZ"]],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E09", "Heating fault.", "dw_heat", 70, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E14", "Water flow / flow sensor / AquaStop related.", "fill", 58, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E22", "Filter / drain restriction.", "dw_drain", 66, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E01", "Water heating / NTC related on some platforms.", "dw_heat", 48, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E02", "Heating circuit.", "dw_heat", 50, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E04", "Water filling / flow.", "fill", 44, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E06", "NTC / temperature.", "thermistor", 46, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E07", "Drying fan / heat-exchanger related on some models.", "dw_heat", 40, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E08", "Heating timeout.", "dw_heat", 42, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E10", "Heating / NTC.", "dw_heat", 40, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E11", "NTC sensor.", "thermistor", 48, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E12", "Heating element related.", "dw_heat", 44, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E13", "NTC out of range.", "thermistor", 40, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E16", "Water inlet / AquaStop.", "fill", 50, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E17", "Flow meter / fill.", "fill", 48, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E20", "Heating pump / heat pump on some SKUs.", "dw_heat", 42, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E21", "Circulation pump blocked or failed.", "motor", 54, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E23", "Heating related.", "dw_heat", 38, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E26", "AquaStop / leak system.", "aquastop", 52, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E27", "Supply voltage out of range.", "power", 40, BD],
  ["Bosch", "bosch", "Washer", "washer", "F17", "Water inlet timeout.", "fill", 72, BW],
  ["Bosch", "bosch", "Washer", "washer", "F18", "Drain timeout.", "drain", 70, BW],
  ["Bosch", "bosch", "Washer", "washer", "F19", "Heating timeout.", "heat", 52, BW],
  ["Bosch", "bosch", "Washer", "washer", "F21", "Drain pump speed / pump fault.", "drain", 58, BW],
  ["Bosch", "bosch", "Washer", "washer", "F23", "AquaStop / leak.", "leak", 60, BW],
  ["Bosch", "bosch", "Washer", "washer", "F43", "Motor / door lock related depending on generation — we start with safe lock and jam checks.", "motor", 40, BW],
  ["Bosch", "bosch", "Washer", "washer", "F44", "Motor control.", "motor", 38, BW],
  ["Bosch", "bosch", "Washer", "washer", "E02", "Door / lock related on some WAN models.", "door", 42, BW],
  ["Bosch", "bosch", "Dryer", "dryer", "E01", "NTC / temperature.", "dryer_heat", 46, ["WTH85200GB", "WTG86400GB"]],
  ["Bosch", "bosch", "Dryer", "dryer", "E02", "Heating circuit.", "dryer_heat", 48, ["WTH85200GB"]],
  ["Bosch", "bosch", "Dryer", "dryer", "E03", "Door / lock.", "door", 40, ["WTH85200GB"]],
  ["Bosch", "bosch", "Oven", "oven", "E005", "Temperature sensor.", "oven_heat", 44, ["HBG5780S6", "HBA5740S0"]],
  ["Bosch", "bosch", "Oven", "oven", "E011", "Communication / control.", "power", 36, ["HBG5780S6"]],
  ["Bosch", "bosch", "Oven", "oven", "E305", "Sensor / pyro related on some pyrolytic ovens — professional path.", "oven_heat", 38, ["HBG5780S6"]],
  ["Miele", "miele", "Washer", "washer", "F10", "Water inlet fault.", "fill", 50, MW],
  ["Miele", "miele", "Washer", "washer", "F11", "Drain fault.", "drain", 56, MW],
  ["Miele", "miele", "Washer", "washer", "F13", "Heating / NTC.", "heat", 40, MW],
  ["Miele", "miele", "Washer", "washer", "F20", "Heating fault.", "heat", 46, MW],
  ["Miele", "miele", "Washer", "washer", "F41", "Electronics / power.", "power", 34, MW],
  ["Miele", "miele", "Washer", "washer", "F47", "Communication between modules.", "power", 32, MW],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F11", "Drain fault.", "dw_drain", 58, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F12", "Water inlet.", "fill", 50, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F13", "Heating / NTC.", "dw_heat", 46, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F24", "Heater / heater relay.", "dw_heat", 42, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F78", "Circulation pump.", "motor", 40, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F87", "Waterproof / leak system.", "aquastop", 48, MD],
  ["Miele", "miele", "Dryer", "dryer", "F1", "NTC inlet / temperature.", "dryer_heat", 40, ["TEF765WP", "TWF760WP"]],
  ["Miele", "miele", "Dryer", "dryer", "F2", "NTC exhaust / temperature.", "dryer_heat", 38, ["TEF765WP"]],
];

export const BATCH2_ERRORS = rows.map((row) =>
  profileFromSeed({
    brand: row[0],
    brand_slug: row[1],
    appliance: row[2],
    appliance_slug: row[3],
    code: row[4],
    meaning: row[5],
    family: row[6],
    demand: row[7],
    models: row[8],
  }),
);
