import { profileFromSeed, type FaultFamily } from "./families";

const SW = ["WW80T554DAN", "WW90T986ASH"];
const LW = ["F4V310WNE", "WM4000HWA"];
const BW = ["WAN282X1GB"];
const BD = ["SMS6ZCI49T"];
const SD = ["DW80R5061US"];
const SDry = ["DVE45R6100W"];
const LDry = ["DLE3600W"];
const SF = ["RF28R7351SR"];
const MW = ["WWD120"];
const MD = ["G7160SCVI"];
const SO = ["NV51K6650SS"];
const SIW = ["WM14N269GB", "WG44G20FG"];
const SID = ["SN25ZI49CE", "SN63HX42VE"];

type Row = [string, string, string, string, string, string, FaultFamily, number, string[]];

const rows: Row[] = [
  ["Samsung", "samsung", "Washer", "washer", "4C", "Water supply error (4C display of the 4E family).", "fill", 78, SW],
  ["Samsung", "samsung", "Washer", "washer", "0E", "Drain error (0E glyph of the OE family).", "drain", 68, SW],
  ["Samsung", "samsung", "Washer", "washer", "UE", "Unbalanced load.", "unbalance", 80, SW],
  ["Samsung", "samsung", "Washer", "washer", "LE", "Leak detected.", "leak", 64, SW],
  ["Samsung", "samsung", "Washer", "washer", "tE", "Temperature sensor error.", "thermistor", 58, SW],
  ["Samsung", "samsung", "Washer", "washer", "dE", "Door error.", "door", 62, SW],
  ["Samsung", "samsung", "Washer", "washer", "bE", "Motor / speed sensor family (bE).", "motor", 40, SW],
  ["Samsung", "samsung", "Washer", "washer", "FE", "Fan / ventilation related on some heat-pump washers — confirm glyph.", "dryer_air", 34, SW],
  ["Samsung", "samsung", "Washer", "washer", "HO", "Hot water inlet path on some models.", "fill", 36, SW],
  ["Samsung", "samsung", "Washer", "washer", "nd", "No drain detected on some displays.", "drain", 50, SW],
  ["Samsung", "samsung", "Washer", "washer", "nF", "No fill detected.", "fill", 48, SW],
  ["Samsung", "samsung", "Washer", "washer", "dc", "Door / unbalanced variant — confirm exact glyphs.", "door", 42, SW],
  ["Samsung", "samsung", "Washer", "washer", "E2", "Button stuck / panel on some models.", "power", 32, SW],
  ["Samsung", "samsung", "Washer", "washer", "E3", "Water level / overflow related on some rows.", "overflow", 34, SW],
  ["Samsung", "samsung", "Washer", "washer", "E7", "Motor / tachometer on older displays.", "motor", 36, SW],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "9E", "Low voltage / power.", "power", 40, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "bE", "Motor related.", "motor", 36, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "CE", "Communication / control.", "power", 34, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "dE", "Door error.", "door", 48, SD],
  ["Samsung", "samsung", "Dishwasher", "dishwasher", "nE", "No water / inlet timeout on some DW rows.", "fill", 44, SD],
  ["Samsung", "samsung", "Dryer", "dryer", "5C", "Drain / condenser pump on heat-pump dryers.", "drain", 46, SDry],
  ["Samsung", "samsung", "Dryer", "dryer", "5E", "Drain error family.", "drain", 44, SDry],
  ["Samsung", "samsung", "Dryer", "dryer", "OE", "Drain overflow on some dryers.", "drain", 40, SDry],
  ["Samsung", "samsung", "Dryer", "dryer", "FE", "Fan error.", "dryer_air", 42, SDry],
  ["Samsung", "samsung", "Dryer", "dryer", "9C", "Low voltage.", "power", 34, SDry],
  ["Samsung", "samsung", "Fridge", "fridge", "1E", "Fridge sensor / defrost family on some displays.", "fridge_sensor", 40, SF],
  ["Samsung", "samsung", "Fridge", "fridge", "4E", "Defrost sensor family.", "fridge_sensor", 38, SF],
  ["Samsung", "samsung", "Fridge", "fridge", "5E", "Freezer sensor family.", "fridge_sensor", 38, SF],
  ["Samsung", "samsung", "Fridge", "fridge", "6E", "Ambient / condenser sensor on some models.", "fridge_sensor", 34, SF],
  ["Samsung", "samsung", "Fridge", "fridge", "8E", "Ice-room / ice-maker sensor on some French-door rows.", "fridge_sensor", 36, SF],
  ["Samsung", "samsung", "Oven", "oven", "E13", "Temperature sensor / communication.", "oven_heat", 38, SO],
  ["Samsung", "samsung", "Oven", "oven", "E15", "Door lock / latch on some ovens.", "door", 36, SO],
  ["Samsung", "samsung", "Oven", "oven", "E24", "Steam / water tank related on steam ovens — not a bake-element guess.", "oven_heat", 34, SO],
  ["LG", "lg", "Washer", "washer", "IE", "Water inlet error.", "fill", 76, LW],
  ["LG", "lg", "Washer", "washer", "OE", "Drain error.", "drain", 78, LW],
  ["LG", "lg", "Washer", "washer", "UE", "Unbalanced load.", "unbalance", 80, LW],
  ["LG", "lg", "Washer", "washer", "dE1", "Door error variant.", "door", 46, LW],
  ["LG", "lg", "Washer", "washer", "dE2", "Door lock variant.", "door", 42, LW],
  ["LG", "lg", "Washer", "washer", "CL", "Child lock is not a fault — confirm before replacing parts.", "door", 40, LW],
  ["LG", "lg", "Washer", "washer", "tb", "Tub / unbalance related on some rows.", "unbalance", 36, LW],
  ["LG", "lg", "Washer", "washer", "PF1", "Power failure variant.", "power", 38, LW],
  ["LG", "lg", "Washer", "washer", "E6", "Motor / hall on some older LG washers.", "motor", 34, LW],
  ["LG", "lg", "Washer", "washer", "E7", "Motor / tachometer.", "motor", 34, LW],
  ["LG", "lg", "Dryer", "dryer", "d80", "Restricted airflow (d80 family).", "dryer_air", 50, LDry],
  ["LG", "lg", "Dryer", "dryer", "d95", "Severe airflow restriction.", "dryer_air", 46, LDry],
  ["LG", "lg", "Dryer", "dryer", "nS", "No spin / motor on some dryers.", "motor", 38, LDry],
  ["LG", "lg", "Dryer", "dryer", "gAS", "Gas dryer ignition path — professional only.", "dryer_heat", 36, LDry],
  ["LG", "lg", "Fridge", "fridge", "Er IF", "Icemaker / fridge sensor family — confirm exact glyphs.", "fridge_sensor", 36, ["LTCS20020S"]],
  ["LG", "lg", "Fridge", "fridge", "Er FS", "Freezer sensor.", "fridge_sensor", 38, ["GSX960NSAZ"]],
  ["LG", "lg", "Fridge", "fridge", "Er dH", "Defrost heater / sensor.", "fridge_sensor", 40, ["GSX960NSAZ"]],
  ["LG", "lg", "Fridge", "fridge", "Er rT", "Room / ambient thermistor.", "fridge_sensor", 34, ["GSX960NSAZ"]],
  ["Bosch", "bosch", "Washer", "washer", "E16", "Door / lock on some WAN platforms.", "door", 44, BW],
  ["Bosch", "bosch", "Washer", "washer", "E17", "Water inlet timeout (E17 family).", "fill", 60, BW],
  ["Bosch", "bosch", "Washer", "washer", "E18", "Drain timeout (E18 family).", "drain", 62, BW],
  ["Bosch", "bosch", "Washer", "washer", "E19", "Heating timeout.", "heat", 48, BW],
  ["Bosch", "bosch", "Washer", "washer", "E20", "Heating / NTC.", "heat", 42, BW],
  ["Bosch", "bosch", "Washer", "washer", "E22", "NTC / temperature.", "thermistor", 44, BW],
  ["Bosch", "bosch", "Washer", "washer", "E23", "AquaStop / leak.", "leak", 56, BW],
  ["Bosch", "bosch", "Washer", "washer", "E25", "NTC / heating.", "heat", 40, BW],
  ["Bosch", "bosch", "Washer", "washer", "E29", "Drain pump.", "drain", 48, BW],
  ["Bosch", "bosch", "Washer", "washer", "E32", "Unbalance / spin.", "unbalance", 50, BW],
  ["Bosch", "bosch", "Washer", "washer", "E33", "Unbalance variant.", "unbalance", 42, BW],
  ["Bosch", "bosch", "Washer", "washer", "E36", "NTC / heating circuit.", "thermistor", 38, BW],
  ["Bosch", "bosch", "Washer", "washer", "F12", "Heating related.", "heat", 40, BW],
  ["Bosch", "bosch", "Washer", "washer", "F13", "NTC.", "thermistor", 42, BW],
  ["Bosch", "bosch", "Washer", "washer", "F14", "NTC / heating.", "heat", 40, BW],
  ["Bosch", "bosch", "Washer", "washer", "F16", "Door lock.", "door", 46, BW],
  ["Bosch", "bosch", "Washer", "washer", "F61", "Door / lock communication.", "door", 38, BW],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E15", "Water in base / AquaStop.", "aquastop", 80, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E24", "Drain hose / drain path.", "dw_drain", 64, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E25", "Drain pump blocked.", "dw_drain", 68, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E03", "Heating / NTC.", "dw_heat", 42, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E05", "NTC / fill.", "fill", 40, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E18", "Water inlet.", "fill", 46, BD],
  ["Bosch", "bosch", "Dishwasher", "dishwasher", "E19", "Heating.", "dw_heat", 40, BD],
  ["Bosch", "bosch", "Dryer", "dryer", "E04", "NTC / temperature.", "dryer_heat", 40, ["WTH85200GB"]],
  ["Bosch", "bosch", "Dryer", "dryer", "E05", "Heating circuit.", "dryer_heat", 42, ["WTH85200GB"]],
  ["Bosch", "bosch", "Dryer", "dryer", "E08", "Door / lock.", "door", 38, ["WTH85200GB"]],
  ["Bosch", "bosch", "Oven", "oven", "E011", "Communication / control.", "power", 36, ["HBG5780S6"]],
  ["Bosch", "bosch", "Oven", "oven", "E101", "Temperature sensor.", "oven_heat", 40, ["HBG5780S6"]],
  ["Bosch", "bosch", "Oven", "oven", "E104", "Sensor / pyro path — professional.", "oven_heat", 34, ["HBG5780S6"]],
  ["Miele", "miele", "Washer", "washer", "F1", "NTC / temperature.", "thermistor", 42, MW],
  ["Miele", "miele", "Washer", "washer", "F2", "NTC variant.", "thermistor", 40, MW],
  ["Miele", "miele", "Washer", "washer", "F3", "NTC / heating.", "heat", 38, MW],
  ["Miele", "miele", "Washer", "washer", "F4", "Heating circuit.", "heat", 40, MW],
  ["Miele", "miele", "Washer", "washer", "F51", "Motor / tachometer.", "motor", 38, MW],
  ["Miele", "miele", "Washer", "washer", "F53", "Motor control.", "motor", 36, MW],
  ["Miele", "miele", "Washer", "washer", "F62", "Door lock.", "door", 42, MW],
  ["Miele", "miele", "Washer", "washer", "F63", "Door lock variant.", "door", 38, MW],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F1", "NTC.", "thermistor", 40, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F2", "NTC variant.", "thermistor", 38, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F14", "Water inlet.", "fill", 46, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F15", "Water inlet variant.", "fill", 42, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F18", "Drain.", "dw_drain", 48, MD],
  ["Miele", "miele", "Dishwasher", "dishwasher", "F19", "Drain variant.", "dw_drain", 44, MD],
  ["Miele", "miele", "Dryer", "dryer", "F3", "NTC.", "dryer_heat", 38, ["TEF765WP"]],
  ["Miele", "miele", "Dryer", "dryer", "F4", "Heating.", "dryer_heat", 40, ["TEF765WP"]],
  ["Miele", "miele", "Dryer", "dryer", "F5", "Heating circuit.", "dryer_heat", 36, ["TEF765WP"]],
  ["Siemens", "siemens", "Washer", "washer", "E17", "Water inlet timeout (Bosch-group platform).", "fill", 64, SIW],
  ["Siemens", "siemens", "Washer", "washer", "E18", "Drain timeout.", "drain", 66, SIW],
  ["Siemens", "siemens", "Washer", "washer", "E19", "Heating timeout.", "heat", 50, SIW],
  ["Siemens", "siemens", "Washer", "washer", "E23", "AquaStop / leak.", "leak", 58, SIW],
  ["Siemens", "siemens", "Washer", "washer", "F17", "Water inlet timeout.", "fill", 70, SIW],
  ["Siemens", "siemens", "Washer", "washer", "F18", "Drain timeout.", "drain", 68, SIW],
  ["Siemens", "siemens", "Washer", "washer", "F19", "Heating timeout.", "heat", 50, SIW],
  ["Siemens", "siemens", "Washer", "washer", "F21", "Drain pump.", "drain", 54, SIW],
  ["Siemens", "siemens", "Washer", "washer", "F23", "AquaStop / leak.", "leak", 56, SIW],
  ["Siemens", "siemens", "Washer", "washer", "F43", "Motor / lock — start with safe lock checks.", "motor", 40, SIW],
  ["Siemens", "siemens", "Washer", "washer", "E32", "Unbalance / spin.", "unbalance", 48, SIW],
  ["Siemens", "siemens", "Washer", "washer", "E29", "Drain pump.", "drain", 46, SIW],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E15", "Water in base / AquaStop.", "aquastop", 78, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E09", "Heating fault.", "dw_heat", 66, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E22", "Filter / drain restriction.", "dw_drain", 64, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E24", "Drain hose.", "dw_drain", 60, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E25", "Drain pump blocked.", "dw_drain", 62, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E14", "Flow / AquaStop related.", "fill", 54, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E16", "Water inlet / AquaStop.", "fill", 50, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E17", "Flow meter / fill.", "fill", 48, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E21", "Circulation pump.", "motor", 50, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E26", "AquaStop / leak system.", "aquastop", 52, SID],
  ["Siemens", "siemens", "Dishwasher", "dishwasher", "E11", "NTC sensor.", "thermistor", 46, SID],
  ["Siemens", "siemens", "Dryer", "dryer", "E01", "NTC / temperature.", "dryer_heat", 44, ["WT47W5W0GB"]],
  ["Siemens", "siemens", "Dryer", "dryer", "E02", "Heating circuit.", "dryer_heat", 46, ["WT47W5W0GB"]],
  ["Siemens", "siemens", "Dryer", "dryer", "E03", "Door / lock.", "door", 40, ["WT47W5W0GB"]],
  ["Siemens", "siemens", "Oven", "oven", "E005", "Temperature sensor.", "oven_heat", 42, ["HB578A0S6"]],
  ["Siemens", "siemens", "Oven", "oven", "E011", "Communication / control.", "power", 36, ["HB578A0S6"]],
  ["Siemens", "siemens", "Oven", "oven", "E305", "Sensor / pyro — professional path.", "oven_heat", 34, ["HB578A0S6"]],
];

export const BATCH3_ERRORS = rows.map((row) =>
  profileFromSeed({
    brand: row[0],
    brand_slug: row[1],
    appliance: row[2],
    appliance_slug: row[3],
    code: row[4],
    meaning: row[5],
    family: row[6],
    demand: row[7],
    models: row[8],
  }),
);
