import { provenance } from "@penta/data-provenance";
import type { DiagnosticQuestion, ErrorProfile, FixCause, SymptomProfile } from "./types";

const RETRIEVED = "2026-08-12T00:00:00.000Z";

function doc(
  brand: string,
  raw: string,
  url: string,
  confidence: number,
) {
  return provenance({
    source_id: `${brand.toLowerCase()}-service-manual`,
    source_type: "MANUFACTURER",
    source_url: url,
    retrieved_at: RETRIEVED,
    valid_from: "2020-01-01",
    valid_until: null,
    confidence,
    raw_value: raw,
    normalized_value: raw,
    verification_method: "MANUFACTURER_DOC",
  });
}

function cause(
  partial: Omit<FixCause, "cost_eur_min" | "cost_eur_max" | "tools"> &
    Partial<Pick<FixCause, "cost_eur_min" | "cost_eur_max" | "tools">>,
): FixCause {
  return {
    tools: ["flashlight"],
    cost_eur_min: 0,
    cost_eur_max: 0,
    ...partial,
  };
}

const waterQuestions = (prefix: string): DiagnosticQuestion[] => [
  {
    id: `${prefix}-tap`,
    text: "Is water reaching the tap normally?",
    why: "If the household supply is weak, the appliance is not the first place to look.",
    answers: [
      {
        id: "yes",
        label: "Yes, normal pressure",
        likelihoods: {
          supply: 0.35,
          filter: 0.9,
          hose: 0.85,
          valve: 0.85,
          sensor: 0.8,
        },
      },
      {
        id: "no",
        label: "No, weak or no water",
        likelihoods: {
          supply: 0.95,
          filter: 0.2,
          hose: 0.15,
          valve: 0.1,
          sensor: 0.05,
        },
      },
      {
        id: "unsure",
        label: "Not sure",
        likelihoods: {
          supply: 0.5,
          filter: 0.5,
          hose: 0.5,
          valve: 0.5,
          sensor: 0.5,
        },
      },
    ],
  },
  {
    id: `${prefix}-fill`,
    text: "Can you hear the washer trying to fill?",
    why: "A fill attempt with no water points to a blocked path or closed valve, not a dead control board.",
    answers: [
      {
        id: "yes",
        label: "Yes, it hums or clicks then stops",
        likelihoods: {
          supply: 0.7,
          filter: 0.85,
          hose: 0.7,
          valve: 0.75,
          sensor: 0.25,
        },
      },
      {
        id: "no",
        label: "No sound at all",
        likelihoods: {
          supply: 0.2,
          filter: 0.2,
          hose: 0.2,
          valve: 0.45,
          sensor: 0.8,
        },
      },
    ],
  },
  {
    id: `${prefix}-kink`,
    text: "Is the inlet hose kinked, frozen, or obviously crushed?",
    why: "A visible hose fault is a high-likelihood, low-risk check before replacing parts.",
    answers: [
      {
        id: "yes",
        label: "Yes",
        likelihoods: {
          supply: 0.1,
          filter: 0.15,
          hose: 0.95,
          valve: 0.1,
          sensor: 0.05,
        },
      },
      {
        id: "no",
        label: "No",
        likelihoods: {
          supply: 0.55,
          filter: 0.7,
          hose: 0.15,
          valve: 0.65,
          sensor: 0.55,
        },
      },
    ],
  },
];

const drainQuestions = (prefix: string): DiagnosticQuestion[] => [
  {
    id: `${prefix}-filter`,
    text: "Have you cleaned the drain pump filter in the last month?",
    why: "Lint and coins in the pump filter are the most common drain faults on recent washers.",
    answers: [
      {
        id: "no",
        label: "No / never",
        likelihoods: { filter: 0.9, hose: 0.45, pump: 0.4, drain: 0.35 },
      },
      {
        id: "yes",
        label: "Yes, it was clear",
        likelihoods: { filter: 0.15, hose: 0.7, pump: 0.7, drain: 0.65 },
      },
    ],
  },
  {
    id: `${prefix}-standpipe`,
    text: "Is the drain hose pushed too far into the standpipe?",
    why: "A siphon or kinked standpipe connection can look like a pump failure.",
    answers: [
      {
        id: "yes",
        label: "Yes, it is jammed in",
        likelihoods: { filter: 0.2, hose: 0.85, pump: 0.25, drain: 0.8 },
      },
      {
        id: "no",
        label: "No, it sits loosely with an air gap",
        likelihoods: { filter: 0.6, hose: 0.25, pump: 0.65, drain: 0.3 },
      },
    ],
  },
];

function samsungWasher(
  code: string,
  meaning: string,
  causes: FixCause[],
  questions: DiagnosticQuestion[],
  demand: number,
  related: string[],
): ErrorProfile {
  return {
    id: `fix:samsung:washer:${code.toLowerCase()}`,
    brand: "Samsung",
    brand_slug: "samsung",
    appliance: "Washer",
    appliance_slug: "washer",
    code,
    code_slug: `${code.toLowerCase()}-error`,
    meaning,
    affected_family: "Samsung front-load washers (WW / WD families)",
    models: ["WW80T554DAN", "WW90T986ASH", "WW70T402LEE", "WF45R6100AW"],
    causes,
    questions,
    related_symptoms: related,
    safety_notes: [
      "Unplug the appliance before removing the drain filter cover.",
      "Do not open the control board or motor housing.",
    ],
    provenance: [
      doc(
        "Samsung",
        `${code} ${meaning}`,
        "https://www.samsung.com/us/support/",
        88,
      ),
    ],
    confidence: "HIGH",
    search_demand: demand,
    coverage: "verified",
  };
}

export const ERRORS: ErrorProfile[] = [
  samsungWasher(
    "4C",
    "Water supply error — the washer did not detect enough inlet water in time.",
    [
      cause({
        id: "supply",
        name: "Household water supply closed or weak",
        prior: 0.35,
        summary: "Tap off, shared pressure drop, or isolation valve not fully open.",
        difficulty: 1,
        time_minutes: 5,
        safety: "SAFE_USER_CHECK",
        fix: "Fully open the isolation valve and confirm other taps have pressure.",
      }),
      cause({
        id: "filter",
        name: "Blocked inlet filter screens",
        prior: 0.25,
        summary: "Mesh filters inside the water inlet catch grit and starve the valve.",
        difficulty: 2,
        time_minutes: 20,
        tools: ["pliers", "towel", "old toothbrush"],
        safety: "SAFE_USER_CHECK",
        fix: "Unplug, turn water off, unscrew hoses, clean the inlet screens, refit without kinks.",
      }),
      cause({
        id: "hose",
        name: "Kinked or blocked inlet hose",
        prior: 0.15,
        summary: "Crushed hose behind the cabinet or a collapsed rubber lining.",
        difficulty: 1,
        time_minutes: 10,
        cost_eur_min: 12,
        cost_eur_max: 25,
        safety: "SAFE_USER_CHECK",
        fix: "Straighten the hose. Replace if the inner lining is collapsed.",
      }),
      cause({
        id: "valve",
        name: "Inlet valve not opening",
        prior: 0.15,
        summary: "The solenoid valve no longer opens when the board calls for water.",
        difficulty: 3,
        time_minutes: 45,
        cost_eur_min: 25,
        cost_eur_max: 70,
        tools: ["screwdriver", "multimeter"],
        safety: "CAUTION",
        fix: "Test valve coil continuity after isolating power. Replace the valve if open-circuit.",
      }),
      cause({
        id: "sensor",
        name: "Water level sensor or control",
        prior: 0.1,
        summary: "The machine fills but the pressure sensor never reports water.",
        difficulty: 4,
        time_minutes: 60,
        cost_eur_min: 40,
        cost_eur_max: 180,
        tools: ["screwdriver", "multimeter"],
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Requires live testing of the pressure sensor and board.",
        fix: "A technician should test the pressure hose, sensor, and board. Do not probe live mains.",
      }),
    ],
    waterQuestions("4c"),
    92,
    ["not-filling", "takes-too-long-to-fill"],
  ),
  samsungWasher(
    "4E",
    "Water supply error (alternate code used on some WW/WF models).",
    [
      cause({
        id: "supply",
        name: "Household water supply closed or weak",
        prior: 0.34,
        summary: "Same family as 4C — inlet water was not detected in time.",
        difficulty: 1,
        time_minutes: 5,
        safety: "SAFE_USER_CHECK",
        fix: "Open the tap fully and retry.",
      }),
      cause({
        id: "filter",
        name: "Blocked inlet filter screens",
        prior: 0.28,
        summary: "Inlet mesh clogged with scale or grit.",
        difficulty: 2,
        time_minutes: 20,
        safety: "SAFE_USER_CHECK",
        fix: "Clean both hot and cold inlet screens if dual-inlet.",
      }),
      cause({
        id: "hose",
        name: "Kinked inlet hose",
        prior: 0.16,
        summary: "Hose crushed behind the machine.",
        difficulty: 1,
        time_minutes: 10,
        safety: "SAFE_USER_CHECK",
        fix: "Pull the machine forward and free the hose.",
      }),
      cause({
        id: "valve",
        name: "Inlet valve",
        prior: 0.14,
        summary: "Valve stuck closed.",
        difficulty: 3,
        time_minutes: 45,
        cost_eur_min: 25,
        cost_eur_max: 70,
        safety: "CAUTION",
        fix: "Replace the inlet valve after isolating water and power.",
      }),
      cause({
        id: "sensor",
        name: "Sensor/control",
        prior: 0.08,
        summary: "Board or sensor not registering fill.",
        difficulty: 4,
        time_minutes: 60,
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Live electrical diagnosis.",
        fix: "Professional diagnosis of the water level system.",
      }),
    ],
    waterQuestions("4e"),
    74,
    ["not-filling"],
  ),
  samsungWasher(
    "5C",
    "Draining error — water did not leave the tub in the expected time.",
    [
      cause({
        id: "filter",
        name: "Blocked drain pump filter",
        prior: 0.42,
        summary: "Coins, lint, or a sock in the front drain trap.",
        difficulty: 2,
        time_minutes: 20,
        tools: ["towel", "shallow tray"],
        safety: "SAFE_USER_CHECK",
        fix: "Open the lower front access, drain residual water, clean the trap.",
      }),
      cause({
        id: "hose",
        name: "Drain hose kinked or too high",
        prior: 0.22,
        summary: "Hose crushed, looped above spec, or jammed in the standpipe.",
        difficulty: 1,
        time_minutes: 10,
        safety: "SAFE_USER_CHECK",
        fix: "Reroute the hose with a gentle bend and an air gap at the standpipe.",
      }),
      cause({
        id: "pump",
        name: "Drain pump jammed or failed",
        prior: 0.24,
        summary: "Pump impeller blocked or motor open-circuit.",
        difficulty: 3,
        time_minutes: 50,
        cost_eur_min: 35,
        cost_eur_max: 90,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Inspect impeller after isolating power. Replace the pump if it does not spin freely.",
      }),
      cause({
        id: "drain",
        name: "Household drain backing up",
        prior: 0.12,
        summary: "Standpipe or sink drain is slow, so the washer cannot empty.",
        difficulty: 2,
        time_minutes: 30,
        safety: "SAFE_USER_CHECK",
        fix: "Test the standpipe with a bucket of water. Clear the household drain if it backs up.",
      }),
    ],
    drainQuestions("5c"),
    88,
    ["not-draining", "standing-water"],
  ),
  samsungWasher(
    "5E",
    "Draining error (SE/5E family on several Samsung washers).",
    [
      cause({
        id: "filter",
        name: "Blocked drain pump filter",
        prior: 0.4,
        summary: "Trap full of lint or a foreign object.",
        difficulty: 2,
        time_minutes: 20,
        safety: "SAFE_USER_CHECK",
        fix: "Clean the pump filter.",
      }),
      cause({
        id: "hose",
        name: "Drain hose restriction",
        prior: 0.24,
        summary: "Kink or standpipe siphon.",
        difficulty: 1,
        time_minutes: 10,
        safety: "SAFE_USER_CHECK",
        fix: "Free and shorten the insertion into the standpipe.",
      }),
      cause({
        id: "pump",
        name: "Drain pump",
        prior: 0.26,
        summary: "Pump not moving water.",
        difficulty: 3,
        time_minutes: 50,
        cost_eur_min: 35,
        cost_eur_max: 90,
        safety: "CAUTION",
        fix: "Replace pump if impeller is free but motor is silent.",
      }),
      cause({
        id: "drain",
        name: "Household drain",
        prior: 0.1,
        summary: "Building drain restriction.",
        difficulty: 2,
        time_minutes: 30,
        safety: "SAFE_USER_CHECK",
        fix: "Verify standpipe flow independently.",
      }),
    ],
    drainQuestions("5e"),
    70,
    ["not-draining"],
  ),
  samsungWasher(
    "UE",
    "Unbalanced load — the drum could not distribute weight for spin.",
    [
      cause({
        id: "load",
        name: "Uneven or single heavy item",
        prior: 0.55,
        summary: "A bath mat, duvet, or one pair of trainers on one side of the drum.",
        difficulty: 1,
        time_minutes: 5,
        safety: "SAFE_USER_CHECK",
        fix: "Redistribute the load, add a few similar items, retry spin.",
      }),
      cause({
        id: "level",
        name: "Machine not level",
        prior: 0.2,
        summary: "Feet not locked, or the cabinet rocks.",
        difficulty: 2,
        time_minutes: 15,
        tools: ["spirit level"],
        safety: "SAFE_USER_CHECK",
        fix: "Level all four feet and tighten lock nuts.",
      }),
      cause({
        id: "shock",
        name: "Damper or shock absorber wear",
        prior: 0.15,
        summary: "Drum continues to bounce after a balanced load.",
        difficulty: 4,
        time_minutes: 90,
        cost_eur_min: 40,
        cost_eur_max: 120,
        safety: "CAUTION",
        fix: "Inspect dampers with the machine unplugged. Replace as a set if leaking or loose.",
      }),
      cause({
        id: "sensor",
        name: "Hall / unbalance sensor",
        prior: 0.1,
        summary: "Control never sees a balanced drum.",
        difficulty: 5,
        time_minutes: 90,
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Requires motor hall-sensor testing.",
        fix: "Technician diagnosis of the motor position sensor.",
      }),
    ],
    [
      {
        id: "ue-retry",
        text: "Did redistributing the load and running spin again clear the code?",
        why: "Most UE events are a one-off heavy item, not a failed part.",
        answers: [
          {
            id: "yes",
            label: "Yes, it spun",
            likelihoods: { load: 0.95, level: 0.2, shock: 0.1, sensor: 0.05 },
          },
          {
            id: "no",
            label: "No, UE returned with a small mixed load",
            likelihoods: { load: 0.2, level: 0.6, shock: 0.7, sensor: 0.55 },
          },
        ],
      },
      {
        id: "ue-rock",
        text: "Does the washer rock or walk during spin?",
        why: "Walking usually means feet, floor, or dampers — not software.",
        answers: [
          {
            id: "yes",
            label: "Yes",
            likelihoods: { load: 0.25, level: 0.85, shock: 0.8, sensor: 0.2 },
          },
          {
            id: "no",
            label: "No, it sits still",
            likelihoods: { load: 0.65, level: 0.2, shock: 0.25, sensor: 0.5 },
          },
        ],
      },
    ],
    86,
    ["wont-spin", "shakes"],
  ),
  samsungWasher(
    "DC",
    "Door lock error — the washer does not confirm the door is locked.",
    [
      cause({
        id: "latch",
        name: "Door not fully closed",
        prior: 0.4,
        summary: "Laundry caught in the seal, or the door needs a firmer push.",
        difficulty: 1,
        time_minutes: 2,
        safety: "SAFE_USER_CHECK",
        fix: "Clear the gasket, close firmly, retry.",
      }),
      cause({
        id: "lock",
        name: "Door lock assembly",
        prior: 0.35,
        summary: "The lock does not pull in or report locked to the board.",
        difficulty: 3,
        time_minutes: 40,
        cost_eur_min: 20,
        cost_eur_max: 55,
        tools: ["screwdriver", "torx"],
        safety: "CAUTION",
        fix: "Replace the door lock after isolating power. Do not force a locked door.",
      }),
      cause({
        id: "wiring",
        name: "Lock wiring / board",
        prior: 0.25,
        summary: "Harness or control not seeing the lock switch.",
        difficulty: 5,
        time_minutes: 70,
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Live circuit on the lock harness.",
        fix: "Technician continuity test of the lock circuit.",
      }),
    ],
    [
      {
        id: "dc-click",
        text: "Do you hear the door lock click when you start a cycle?",
        why: "A click with DC still present points past a simple ajar door.",
        answers: [
          {
            id: "no",
            label: "No click",
            likelihoods: { latch: 0.55, lock: 0.7, wiring: 0.6 },
          },
          {
            id: "yes",
            label: "Yes, it clicks then errors",
            likelihoods: { latch: 0.2, lock: 0.6, wiring: 0.7 },
          },
        ],
      },
    ],
    69,
    ["door-wont-lock"],
  ),
  samsungWasher(
    "OE",
    "Overflow / too much water detected in the tub.",
    [
      cause({
        id: "valve",
        name: "Inlet valve stuck open",
        prior: 0.4,
        summary: "Water keeps entering after the board stops calling for it.",
        difficulty: 3,
        time_minutes: 40,
        cost_eur_min: 25,
        cost_eur_max: 70,
        safety: "CAUTION",
        fix: "Turn the water off immediately. Replace the inlet valve.",
      }),
      cause({
        id: "sensor",
        name: "Pressure sensor / air hose",
        prior: 0.35,
        summary: "Blocked pressure hose fools the board into overfilling or reporting overflow.",
        difficulty: 3,
        time_minutes: 40,
        safety: "CAUTION",
        fix: "Inspect and clear the pressure hose with power isolated.",
      }),
      cause({
        id: "drain",
        name: "Failed drain during a fill-heavy cycle",
        prior: 0.25,
        summary: "Water is entering faster than it can leave.",
        difficulty: 2,
        time_minutes: 25,
        safety: "SAFE_USER_CHECK",
        fix: "Clean the drain filter and check the hose, then retry.",
      }),
    ],
    [
      {
        id: "oe-water",
        text: "Is water still entering with the cycle cancelled?",
        why: "Uncontrolled fill is an inlet valve that must be isolated at the tap.",
        answers: [
          {
            id: "yes",
            label: "Yes — shut the tap",
            likelihoods: { valve: 0.95, sensor: 0.2, drain: 0.1 },
          },
          {
            id: "no",
            label: "No, fill stops",
            likelihoods: { valve: 0.2, sensor: 0.7, drain: 0.65 },
          },
        ],
      },
    ],
    64,
    ["leaking", "overfilling"],
  ),
  samsungWasher(
    "LE",
    "Leak detected by the base moisture sensor (on models with Aqua Stop / leak sensor).",
    [
      cause({
        id: "filter",
        name: "Drain filter cover not sealed",
        prior: 0.3,
        summary: "After cleaning the trap, the cap was not tightened.",
        difficulty: 1,
        time_minutes: 5,
        safety: "SAFE_USER_CHECK",
        fix: "Refit the filter cap firmly and dry the base tray.",
      }),
      cause({
        id: "door",
        name: "Door boot gasket leak",
        prior: 0.28,
        summary: "A split in the rubber boot drips into the base.",
        difficulty: 3,
        time_minutes: 60,
        cost_eur_min: 30,
        cost_eur_max: 80,
        safety: "CAUTION",
        fix: "Inspect the gasket. Replace if torn. Do not run until dry.",
      }),
      cause({
        id: "hose",
        name: "Internal hose clamp",
        prior: 0.22,
        summary: "A clamp in the cabinet is weeping.",
        difficulty: 4,
        time_minutes: 70,
        safety: "CAUTION",
        fix: "Inspect hoses with the machine unplugged and the back panel off.",
      }),
      cause({
        id: "sensor",
        name: "Damp base / false sensor",
        prior: 0.2,
        summary: "Old water in the base still trips the sensor.",
        difficulty: 2,
        time_minutes: 20,
        safety: "SAFE_USER_CHECK",
        fix: "Dry the base completely, then reset.",
      }),
    ],
    [
      {
        id: "le-wet",
        text: "Is there standing water in the base or on the floor?",
        why: "A dry base with LE suggests residual moisture or a sensitive sensor, not an active flood.",
        answers: [
          {
            id: "yes",
            label: "Yes, it is wet",
            likelihoods: { filter: 0.6, door: 0.7, hose: 0.7, sensor: 0.2 },
          },
          {
            id: "no",
            label: "No visible water",
            likelihoods: { filter: 0.25, door: 0.2, hose: 0.2, sensor: 0.8 },
          },
        ],
      },
    ],
    61,
    ["leaking"],
  ),
  samsungWasher(
    "tE",
    "Temperature sensor (thermistor) error.",
    [
      cause({
        id: "thermistor",
        name: "Faulty thermistor",
        prior: 0.55,
        summary: "The temperature probe is open or shorted.",
        difficulty: 3,
        time_minutes: 40,
        cost_eur_min: 12,
        cost_eur_max: 35,
        safety: "CAUTION",
        fix: "Replace the thermistor after isolating power. Do not bypass it.",
      }),
      cause({
        id: "wiring",
        name: "Harness / connector",
        prior: 0.25,
        summary: "Oxidised connector on the heater tank.",
        difficulty: 3,
        time_minutes: 35,
        safety: "CAUTION",
        fix: "Reseat the connector with power off.",
      }),
      cause({
        id: "board",
        name: "Control board",
        prior: 0.2,
        summary: "Board not reading a valid temperature.",
        difficulty: 5,
        time_minutes: 80,
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Mains heater circuit.",
        fix: "Technician diagnosis. Do not test the heater live.",
      }),
    ],
    [
      {
        id: "te-heat",
        text: "Does the washer still heat on a 60°C cotton cycle?",
        why: "A cold 60°C wash supports a thermistor or heater path fault.",
        answers: [
          {
            id: "no",
            label: "Stays cold",
            likelihoods: { thermistor: 0.7, wiring: 0.6, board: 0.5 },
          },
          {
            id: "yes",
            label: "It heats but still codes",
            likelihoods: { thermistor: 0.45, wiring: 0.4, board: 0.6 },
          },
        ],
      },
    ],
    48,
    ["not-heating"],
  ),
  samsungWasher(
    "3C",
    "Motor / hall sensor error — the drum drive is not reporting rotation correctly.",
    [
      cause({
        id: "object",
        name: "Object jammed between drum and tub",
        prior: 0.3,
        summary: "A bra wire or coin stalling the drum.",
        difficulty: 2,
        time_minutes: 25,
        safety: "SAFE_USER_CHECK",
        fix: "Inspect the drum gap with a flashlight. Remove debris. Do not force the drum.",
      }),
      cause({
        id: "connector",
        name: "Motor connector",
        prior: 0.25,
        summary: "Loose plug on the inverter or hall sensor.",
        difficulty: 3,
        time_minutes: 40,
        safety: "CAUTION",
        fix: "Reseat connectors with power isolated.",
      }),
      cause({
        id: "hall",
        name: "Hall sensor / rotor",
        prior: 0.25,
        summary: "Position sensor failed.",
        difficulty: 4,
        time_minutes: 70,
        cost_eur_min: 30,
        cost_eur_max: 140,
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Inverter/motor live circuits.",
        fix: "Technician motor diagnosis.",
      }),
      cause({
        id: "inverter",
        name: "Inverter / control",
        prior: 0.2,
        summary: "Drive electronics not powering the motor.",
        difficulty: 5,
        time_minutes: 90,
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "High-voltage inverter.",
        fix: "Do not open the inverter housing.",
      }),
    ],
    [
      {
        id: "3c-turn",
        text: "Can you turn the drum by hand with the machine unplugged?",
        why: "A locked drum is a jam or seized bearing, not a software reset.",
        answers: [
          {
            id: "no",
            label: "Drum is locked",
            likelihoods: { object: 0.85, connector: 0.15, hall: 0.2, inverter: 0.1 },
          },
          {
            id: "yes",
            label: "Turns freely",
            likelihoods: { object: 0.15, connector: 0.6, hall: 0.7, inverter: 0.65 },
          },
        ],
      },
    ],
    58,
    ["wont-spin", "dead-drum"],
  ),
];
