import { provenance } from "@penta/data-provenance";
import type { SymptomProfile } from "./types";

const RETRIEVED = "2026-08-12T00:00:00.000Z";

function thirdParty(raw: string, confidence: number) {
  return provenance({
    source_id: "fixcode-service-corpus",
    source_type: "PRIMARY_DATABASE",
    source_name: "FixCode service corpus",
    retrieved_at: RETRIEVED,
    valid_from: "2024-01-01",
    valid_until: null,
    confidence,
    raw_value: raw,
    normalized_value: raw,
    verification_method: "CROSS_SOURCE",
    notes: "Aggregated from manufacturer codes plus consistent field reports. Not a substitute for the model service manual.",
    locator: {
      dataset: "fixcode-service-corpus",
      document_title: "FixCode service corpus",
      section: raw,
    },
  });
}

export const SYMPTOMS: SymptomProfile[] = [
  {
    id: "fix:samsung:washer:not-draining",
    brand: "Samsung",
    brand_slug: "samsung",
    appliance: "Washer",
    appliance_slug: "washer",
    symptom: "Not draining",
    symptom_slug: "not-draining",
    meaning: "Water remains in the drum at the end of a cycle, or the machine pauses before spin.",
    likely_codes: ["5C", "5E", "OE"],
    causes: [
      {
        id: "filter",
        name: "Drain pump filter",
        prior: 0.45,
        summary: "Trap full.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["towel"],
        safety: "SAFE_USER_CHECK",
        fix: "Clean the front drain filter.",
      },
      {
        id: "hose",
        name: "Drain hose",
        prior: 0.25,
        summary: "Kink or standpipe.",
        difficulty: 1,
        time_minutes: 10,
        cost_eur_min: 0,
        cost_eur_max: 18,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Free the hose.",
      },
      {
        id: "pump",
        name: "Drain pump",
        prior: 0.3,
        summary: "Pump not moving water.",
        difficulty: 3,
        time_minutes: 50,
        cost_eur_min: 35,
        cost_eur_max: 90,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Inspect/replace pump.",
      },
    ],
    questions: [
      {
        id: "sym-drain-filter",
        text: "Have you opened the pump filter?",
        why: "Standing water is usually the user-accessible trap.",
        answers: [
          {
            id: "no",
            label: "Not yet",
            likelihoods: { filter: 0.8, hose: 0.5, pump: 0.45 },
          },
          {
            id: "clean",
            label: "Yes, it was clear",
            likelihoods: { filter: 0.15, hose: 0.7, pump: 0.75 },
          },
        ],
      },
    ],
    provenance: [thirdParty("Samsung washer not draining", 78)],
    confidence: "MEDIUM",
    search_demand: 90,
  },
  {
    id: "fix:samsung:washer:wont-spin",
    brand: "Samsung",
    brand_slug: "samsung",
    appliance: "Washer",
    appliance_slug: "washer",
    symptom: "Won't spin",
    symptom_slug: "wont-spin",
    meaning: "The drum washes or tumbles but never reaches spin speed.",
    likely_codes: ["UE", "3C", "DC"],
    causes: [
      {
        id: "load",
        name: "Unbalanced or oversized load",
        prior: 0.4,
        summary: "The machine refuses to spin to protect itself.",
        difficulty: 1,
        time_minutes: 5,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Remove a bulky item and retry spin.",
      },
      {
        id: "drain",
        name: "Still holding water",
        prior: 0.3,
        summary: "Spin is blocked until the tub empties.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["towel"],
        safety: "SAFE_USER_CHECK",
        fix: "Resolve draining first.",
      },
      {
        id: "door",
        name: "Door lock not confirmed",
        prior: 0.15,
        summary: "No spin with an unlocked door.",
        difficulty: 2,
        time_minutes: 10,
        cost_eur_min: 0,
        cost_eur_max: 55,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Confirm the lock clicks.",
      },
      {
        id: "motor",
        name: "Drive / hall sensor",
        prior: 0.15,
        summary: "Motor not reporting rotation.",
        difficulty: 5,
        time_minutes: 80,
        cost_eur_min: 40,
        cost_eur_max: 180,
        tools: ["multimeter"],
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Inverter circuit.",
        fix: "Professional motor diagnosis.",
      },
    ],
    questions: [
      {
        id: "spin-water",
        text: "Is there still water in the drum?",
        why: "A wet tub will not be allowed to spin.",
        answers: [
          {
            id: "yes",
            label: "Yes",
            likelihoods: { load: 0.2, drain: 0.9, door: 0.2, motor: 0.15 },
          },
          {
            id: "no",
            label: "No, it is empty",
            likelihoods: { load: 0.7, drain: 0.15, door: 0.5, motor: 0.55 },
          },
        ],
      },
    ],
    provenance: [thirdParty("Samsung washer won't spin", 80)],
    confidence: "MEDIUM",
    search_demand: 87,
  },
  {
    id: "fix:lg:washer:not-draining",
    brand: "LG",
    brand_slug: "lg",
    appliance: "Washer",
    appliance_slug: "washer",
    symptom: "Not draining",
    symptom_slug: "not-draining",
    meaning: "LG washer holds water and often shows OE.",
    likely_codes: ["OE"],
    causes: [
      {
        id: "filter",
        name: "Drain filter",
        prior: 0.5,
        summary: "Trap blocked.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["towel"],
        safety: "SAFE_USER_CHECK",
        fix: "Clean the filter.",
      },
      {
        id: "hose",
        name: "Drain hose",
        prior: 0.2,
        summary: "Height or kink.",
        difficulty: 1,
        time_minutes: 10,
        cost_eur_min: 0,
        cost_eur_max: 18,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Correct hose route.",
      },
      {
        id: "pump",
        name: "Pump",
        prior: 0.3,
        summary: "Pump jammed.",
        difficulty: 3,
        time_minutes: 45,
        cost_eur_min: 30,
        cost_eur_max: 85,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Clear impeller or replace pump.",
      },
    ],
    questions: [
      {
        id: "lg-sym-filter",
        text: "Did anything come out of the drain filter (coin, sock, lint mat)?",
        why: "OE + standing water is usually the trap.",
        answers: [
          {
            id: "yes",
            label: "Yes",
            likelihoods: { filter: 0.92, hose: 0.2, pump: 0.2 },
          },
          {
            id: "no",
            label: "Nothing there",
            likelihoods: { filter: 0.2, hose: 0.65, pump: 0.7 },
          },
        ],
      },
    ],
    provenance: [thirdParty("LG washer not draining", 82)],
    confidence: "MEDIUM",
    search_demand: 85,
  },
  {
    id: "fix:bosch:dishwasher:leaking",
    brand: "Bosch",
    brand_slug: "bosch",
    appliance: "Dishwasher",
    appliance_slug: "dishwasher",
    symptom: "Leaking",
    symptom_slug: "leaking",
    meaning: "Water on the floor or E15 on the display.",
    likely_codes: ["E15"],
    causes: [
      {
        id: "door",
        name: "Door gasket",
        prior: 0.28,
        summary: "Gasket nicked or dirty.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 35,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Clean the gasket; replace if split.",
      },
      {
        id: "float",
        name: "Water in base / AquaStop",
        prior: 0.42,
        summary: "Base float tripped.",
        difficulty: 2,
        time_minutes: 30,
        cost_eur_min: 0,
        cost_eur_max: 80,
        tools: ["towel"],
        safety: "SAFE_USER_CHECK",
        fix: "Dry the base and find the leak source before running again.",
      },
      {
        id: "hose",
        name: "Door or inlet hose",
        prior: 0.3,
        summary: "Hose behind the kick plate.",
        difficulty: 3,
        time_minutes: 40,
        cost_eur_min: 15,
        cost_eur_max: 80,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Inspect hoses with water and power isolated.",
      },
    ],
    questions: [
      {
        id: "bosch-leak-where",
        text: "Where is the water?",
        why: "Front-center puddles are often the door. Under-kickplate water is the base float.",
        answers: [
          {
            id: "front",
            label: "In front of the door",
            likelihoods: { door: 0.85, float: 0.3, hose: 0.25 },
          },
          {
            id: "under",
            label: "Under / behind the kick plate",
            likelihoods: { door: 0.2, float: 0.8, hose: 0.7 },
          },
        ],
      },
    ],
    provenance: [thirdParty("Bosch dishwasher leaking", 80)],
    confidence: "MEDIUM",
    search_demand: 78,
  },
];

export const APPLIANCES = [
  { slug: "washer", name: "Washer", blurb: "Fill, drain, spin, leak, and door faults." },
  { slug: "dishwasher", name: "Dishwasher", blurb: "AquaStop, drain, and heat faults." },
  { slug: "dryer", name: "Dryer", blurb: "Airflow and moisture-sensor faults." },
  { slug: "fridge", name: "Fridge", blurb: "Sensor and defrost faults — professional-first." },
  { slug: "oven", name: "Oven", blurb: "Coverage is limited in this batch." },
  { slug: "coffee", name: "Coffee machine", blurb: "Not in the verified launch set." },
  { slug: "vacuum", name: "Vacuum", blurb: "Not in the verified launch set." },
  { slug: "ac", name: "Air conditioner", blurb: "Not in the verified launch set." },
] as const;

export const BRANDS = [
  { slug: "samsung", name: "Samsung" },
  { slug: "lg", name: "LG" },
  { slug: "bosch", name: "Bosch" },
  { slug: "miele", name: "Miele" },
  { slug: "siemens", name: "Siemens" },
  { slug: "aeg", name: "AEG" },
  { slug: "electrolux", name: "Electrolux" },
  { slug: "whirlpool", name: "Whirlpool" },
  { slug: "beko", name: "Beko" },
  { slug: "candy", name: "Candy" },
  { slug: "hotpoint", name: "Hotpoint" },
] as const;

export const UNSUPPORTED_NOTE =
  "We only publish diagnostics with a verified cause tree. If your brand is missing, we do not invent a procedure.";
