import { provenance } from "@penta/data-provenance";
import type { ErrorProfile, FixCause } from "./types";

const RETRIEVED = "2026-08-12T00:00:00.000Z";

function doc(brand: string, raw: string, url: string, confidence: number) {
  return provenance({
    source_id: `${brand.toLowerCase()}-support`,
    source_type: "MANUFACTURER",
    source_url: url,
    retrieved_at: RETRIEVED,
    valid_from: "2018-01-01",
    valid_until: null,
    confidence,
    raw_value: raw,
    normalized_value: raw,
    verification_method: "MANUFACTURER_DOC",
  });
}

function cause(partial: FixCause): FixCause {
  return partial;
}

function profile(
  brand: string,
  brand_slug: string,
  appliance: string,
  appliance_slug: string,
  code: string,
  meaning: string,
  family: string,
  models: string[],
  causes: FixCause[],
  demand: number,
  related: string[],
  questions: ErrorProfile["questions"],
  url: string,
): ErrorProfile {
  return {
    id: `fix:${brand_slug}:${appliance_slug}:${code.toLowerCase()}`,
    brand,
    brand_slug,
    appliance,
    appliance_slug,
    code,
    code_slug: `${code.toLowerCase()}-error`,
    meaning,
    affected_family: family,
    models,
    causes,
    questions,
    related_symptoms: related,
    safety_notes: [
      "Isolate power before removing panels or filters that expose wiring.",
      "Do not bypass safety interlocks.",
    ],
    provenance: [doc(brand, `${code} ${meaning}`, url, 86)],
    confidence: "HIGH",
    search_demand: demand,
    coverage: "verified",
  };
}

export const MORE_ERRORS: ErrorProfile[] = [
  profile(
    "LG",
    "lg",
    "Washer",
    "washer",
    "IE",
    "Water inlet error — fill was not detected in time.",
    "LG front-load washers (F / WM families)",
    ["F4V310WNE", "WM4000HWA", "F14WD85EN2"],
    [
      cause({
        id: "supply",
        name: "Tap closed or weak pressure",
        prior: 0.36,
        summary: "No household water at the valve.",
        difficulty: 1,
        time_minutes: 5,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Open the tap and confirm pressure at another faucet.",
      }),
      cause({
        id: "filter",
        name: "Inlet filter mesh",
        prior: 0.28,
        summary: "Grit in the inlet screens.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["pliers"],
        safety: "SAFE_USER_CHECK",
        fix: "Clean the inlet filters.",
      }),
      cause({
        id: "hose",
        name: "Inlet hose",
        prior: 0.16,
        summary: "Kinked hose.",
        difficulty: 1,
        time_minutes: 10,
        cost_eur_min: 12,
        cost_eur_max: 22,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Straighten or replace the hose.",
      }),
      cause({
        id: "valve",
        name: "Inlet valve",
        prior: 0.2,
        summary: "Valve not opening.",
        difficulty: 3,
        time_minutes: 40,
        cost_eur_min: 22,
        cost_eur_max: 60,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Replace the valve with power and water isolated.",
      }),
    ],
    84,
    ["not-filling"],
    [
      {
        id: "lg-ie-tap",
        text: "Is the water tap fully open?",
        why: "IE is a timed fill. Household supply is the first split.",
        answers: [
          {
            id: "yes",
            label: "Yes",
            likelihoods: { supply: 0.25, filter: 0.8, hose: 0.75, valve: 0.75 },
          },
          {
            id: "no",
            label: "No",
            likelihoods: { supply: 0.95, filter: 0.2, hose: 0.2, valve: 0.15 },
          },
        ],
      },
    ],
    "https://www.lg.com/us/support",
  ),
  profile(
    "LG",
    "lg",
    "Washer",
    "washer",
    "OE",
    "Drain error — the tub did not empty in time.",
    "LG front-load washers",
    ["F4V310WNE", "WM4000HWA"],
    [
      cause({
        id: "filter",
        name: "Drain filter / pump trap",
        prior: 0.44,
        summary: "Foreign object in the pump filter.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["towel"],
        safety: "SAFE_USER_CHECK",
        fix: "Clean the drain filter.",
      }),
      cause({
        id: "hose",
        name: "Drain hose height or kink",
        prior: 0.22,
        summary: "Hose above spec or crushed.",
        difficulty: 1,
        time_minutes: 10,
        cost_eur_min: 0,
        cost_eur_max: 18,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Set hose height per the install diagram.",
      }),
      cause({
        id: "pump",
        name: "Drain pump",
        prior: 0.34,
        summary: "Pump not moving water.",
        difficulty: 3,
        time_minutes: 50,
        cost_eur_min: 30,
        cost_eur_max: 85,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Inspect impeller, replace pump if seized.",
      }),
    ],
    90,
    ["not-draining"],
    [
      {
        id: "lg-oe-filter",
        text: "Is the drain filter packed with lint or an object?",
        why: "OE on LG washers is most often the user-accessible trap.",
        answers: [
          {
            id: "yes",
            label: "Yes",
            likelihoods: { filter: 0.92, hose: 0.2, pump: 0.2 },
          },
          {
            id: "no",
            label: "Filter was clean",
            likelihoods: { filter: 0.15, hose: 0.65, pump: 0.75 },
          },
        ],
      },
    ],
    "https://www.lg.com/us/support",
  ),
  profile(
    "LG",
    "lg",
    "Washer",
    "washer",
    "UE",
    "Unbalanced load detected during spin.",
    "LG front-load washers",
    ["F4V310WNE", "WM4000HWA"],
    [
      cause({
        id: "load",
        name: "Unbalanced load",
        prior: 0.6,
        summary: "Single heavy item.",
        difficulty: 1,
        time_minutes: 5,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Redistribute and retry.",
      }),
      cause({
        id: "level",
        name: "Feet / level",
        prior: 0.25,
        summary: "Cabinet rocks.",
        difficulty: 2,
        time_minutes: 15,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["spirit level"],
        safety: "SAFE_USER_CHECK",
        fix: "Level the feet.",
      }),
      cause({
        id: "shock",
        name: "Dampers",
        prior: 0.15,
        summary: "Worn suspension.",
        difficulty: 4,
        time_minutes: 80,
        cost_eur_min: 40,
        cost_eur_max: 110,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Replace dampers as a set.",
      }),
    ],
    80,
    ["wont-spin"],
    [
      {
        id: "lg-ue-item",
        text: "Was there a single heavy item (duvet, trainers, bath mat)?",
        why: "UE is designed to protect the drum from a walking spin.",
        answers: [
          {
            id: "yes",
            label: "Yes",
            likelihoods: { load: 0.9, level: 0.25, shock: 0.15 },
          },
          {
            id: "no",
            label: "Mixed small load",
            likelihoods: { load: 0.25, level: 0.7, shock: 0.65 },
          },
        ],
      },
    ],
    "https://www.lg.com/us/support",
  ),
  profile(
    "LG",
    "lg",
    "Washer",
    "washer",
    "DE",
    "Door error — lock not confirmed.",
    "LG front-load washers",
    ["WM4000HWA"],
    [
      cause({
        id: "ajar",
        name: "Door ajar / laundry in seal",
        prior: 0.45,
        summary: "Door not fully latched.",
        difficulty: 1,
        time_minutes: 2,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Clear the gasket and close firmly.",
      }),
      cause({
        id: "lock",
        name: "Door lock",
        prior: 0.4,
        summary: "Lock actuator or switch.",
        difficulty: 3,
        time_minutes: 40,
        cost_eur_min: 18,
        cost_eur_max: 50,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Replace the lock assembly with power off.",
      }),
      cause({
        id: "board",
        name: "Control / wiring",
        prior: 0.15,
        summary: "Lock circuit not read.",
        difficulty: 5,
        time_minutes: 70,
        cost_eur_min: 80,
        cost_eur_max: 220,
        tools: ["multimeter"],
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Live lock circuit.",
        fix: "Technician test of the lock circuit.",
      }),
    ],
    62,
    ["door-wont-lock"],
    [
      {
        id: "lg-de-close",
        text: "Does the door click shut without laundry in the seal?",
        why: "A mechanical miss is cheaper than a lock replacement.",
        answers: [
          {
            id: "yes",
            label: "Yes, it clicks",
            likelihoods: { ajar: 0.2, lock: 0.75, board: 0.6 },
          },
          {
            id: "no",
            label: "It will not catch",
            likelihoods: { ajar: 0.7, lock: 0.6, board: 0.2 },
          },
        ],
      },
    ],
    "https://www.lg.com/us/support",
  ),
  profile(
    "Bosch",
    "bosch",
    "Dishwasher",
    "dishwasher",
    "E15",
    "Water in the base tray (AquaStop leak protection tripped).",
    "Bosch dishwashers with AquaStop (SMS / SMV / SHP)",
    ["SMS6ZCI49T", "SHPM88Z75N", "SMV4HVX38G"],
    [
      cause({
        id: "spray",
        name: "Overfoaming / rinse aid leak into base",
        prior: 0.22,
        summary: "Too much detergent or a leak into the float tray.",
        difficulty: 2,
        time_minutes: 30,
        cost_eur_min: 0,
        cost_eur_max: 8,
        tools: ["towel"],
        safety: "SAFE_USER_CHECK",
        fix: "Bail water from the base, dry the float, run without extra detergent.",
      }),
      cause({
        id: "hose",
        name: "Internal hose or sump leak",
        prior: 0.33,
        summary: "Water reached the base float switch.",
        difficulty: 4,
        time_minutes: 80,
        cost_eur_min: 0,
        cost_eur_max: 90,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Inspect sump and hoses after isolating power and water.",
      }),
      cause({
        id: "inlet",
        name: "AquaStop inlet hose",
        prior: 0.25,
        summary: "Double-walled inlet hose has taken water into its jacket.",
        difficulty: 2,
        time_minutes: 25,
        cost_eur_min: 35,
        cost_eur_max: 80,
        tools: ["pliers"],
        safety: "SAFE_USER_CHECK",
        fix: "Replace the AquaStop inlet hose. Do not bypass the valve.",
      }),
      cause({
        id: "float",
        name: "Float stuck up",
        prior: 0.2,
        summary: "Base is dry but the float never dropped.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 15,
        tools: ["screwdriver"],
        safety: "SAFE_USER_CHECK",
        fix: "Access the base, free the float, dry thoroughly.",
      }),
    ],
    94,
    ["leaking", "will-not-start"],
    [
      {
        id: "e15-base",
        text: "Is there water in the dishwasher base when you tilt the kick plate?",
        why: "E15 is a float in the base. Dry base vs wet base splits false trip from active leak.",
        answers: [
          {
            id: "yes",
            label: "Yes, base is wet",
            likelihoods: { spray: 0.5, hose: 0.8, inlet: 0.6, float: 0.15 },
          },
          {
            id: "no",
            label: "Base looks dry",
            likelihoods: { spray: 0.2, hose: 0.15, inlet: 0.25, float: 0.85 },
          },
        ],
      },
    ],
    "https://www.bosch-home.com/us/service",
  ),
  profile(
    "Bosch",
    "bosch",
    "Dishwasher",
    "dishwasher",
    "E24",
    "Draining fault — water not leaving the sump.",
    "Bosch dishwashers",
    ["SMS6ZCI49T", "SHPM88Z75N"],
    [
      cause({
        id: "filter",
        name: "Filter / food chopper blockage",
        prior: 0.4,
        summary: "Filter cylinder packed with food.",
        difficulty: 1,
        time_minutes: 15,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Remove and rinse the filter assembly.",
      }),
      cause({
        id: "hose",
        name: "Drain hose / air gap / disposal knockout",
        prior: 0.35,
        summary: "Hose kinked or disposal knockout still in place.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 20,
        tools: ["pliers"],
        safety: "SAFE_USER_CHECK",
        fix: "Check hose route and the disposal inlet.",
      }),
      cause({
        id: "pump",
        name: "Drain pump",
        prior: 0.25,
        summary: "Pump impeller jammed by glass.",
        difficulty: 3,
        time_minutes: 40,
        cost_eur_min: 25,
        cost_eur_max: 70,
        tools: ["screwdriver", "tweezers"],
        safety: "CAUTION",
        fix: "Clear glass from the pump cover. Replace pump if noisy and jammed.",
      }),
    ],
    81,
    ["not-draining", "standing-water"],
    [
      {
        id: "e24-filter",
        text: "Is the filter cylinder clogged?",
        why: "Bosch E24 is usually a user-accessible restriction.",
        answers: [
          {
            id: "yes",
            label: "Yes",
            likelihoods: { filter: 0.9, hose: 0.25, pump: 0.2 },
          },
          {
            id: "no",
            label: "Filter is clean",
            likelihoods: { filter: 0.15, hose: 0.7, pump: 0.7 },
          },
        ],
      },
    ],
    "https://www.bosch-home.com/us/service",
  ),
  profile(
    "Bosch",
    "bosch",
    "Dishwasher",
    "dishwasher",
    "E25",
    "Drain pump blocked or not running.",
    "Bosch dishwashers",
    ["SMV4HVX38G"],
    [
      cause({
        id: "glass",
        name: "Broken glass in pump",
        prior: 0.5,
        summary: "Shard jammed in the impeller.",
        difficulty: 2,
        time_minutes: 25,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["tweezers"],
        safety: "CAUTION",
        fix: "Remove the pump cover and extract glass. Wear gloves.",
      }),
      cause({
        id: "pump",
        name: "Drain pump failed",
        prior: 0.35,
        summary: "Pump motor open or seized.",
        difficulty: 3,
        time_minutes: 50,
        cost_eur_min: 30,
        cost_eur_max: 80,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Replace the drain pump with power isolated.",
      }),
      cause({
        id: "wiring",
        name: "Pump wiring",
        prior: 0.15,
        summary: "Connector off the pump.",
        difficulty: 4,
        time_minutes: 40,
        cost_eur_min: 0,
        cost_eur_max: 20,
        tools: ["screwdriver"],
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Mains on the pump circuit.",
        fix: "Technician continuity test.",
      }),
    ],
    72,
    ["not-draining"],
    [
      {
        id: "e25-noise",
        text: "Does the pump buzz but not drain?",
        why: "A buzz with no water movement is almost always an impeller jam.",
        answers: [
          {
            id: "yes",
            label: "Buzz, no drain",
            likelihoods: { glass: 0.85, pump: 0.45, wiring: 0.2 },
          },
          {
            id: "silent",
            label: "Completely silent",
            likelihoods: { glass: 0.2, pump: 0.7, wiring: 0.75 },
          },
        ],
      },
    ],
    "https://www.bosch-home.com/us/service",
  ),
  profile(
    "Bosch",
    "bosch",
    "Washer",
    "washer",
    "E18",
    "Water drain timeout on Bosch washers.",
    "Bosch / Siemens washers (WAN / WAU)",
    ["WAN282X1GB", "WAU28PH9GB"],
    [
      cause({
        id: "filter",
        name: "Coin trap / pump filter",
        prior: 0.48,
        summary: "Blocked pump filter.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["towel"],
        safety: "SAFE_USER_CHECK",
        fix: "Drain via the service hose, then clean the trap.",
      }),
      cause({
        id: "hose",
        name: "Drain hose",
        prior: 0.22,
        summary: "Kink or blocked standpipe.",
        difficulty: 1,
        time_minutes: 10,
        cost_eur_min: 0,
        cost_eur_max: 18,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Reroute the hose.",
      }),
      cause({
        id: "pump",
        name: "Drain pump",
        prior: 0.3,
        summary: "Pump failed.",
        difficulty: 3,
        time_minutes: 50,
        cost_eur_min: 35,
        cost_eur_max: 90,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Replace pump after confirming the trap is clear.",
      }),
    ],
    68,
    ["not-draining"],
    [
      {
        id: "bosch-e18",
        text: "Did water run out of the emergency drain hose?",
        why: "If the emergency hose flows, the tub is not the restriction.",
        answers: [
          {
            id: "yes",
            label: "Yes, it drained",
            likelihoods: { filter: 0.7, hose: 0.6, pump: 0.45 },
          },
          {
            id: "no",
            label: "Little or no water",
            likelihoods: { filter: 0.35, hose: 0.25, pump: 0.6 },
          },
        ],
      },
    ],
    "https://www.bosch-home.com/us/service",
  ),
  profile(
    "Miele",
    "miele",
    "Washer",
    "washer",
    "F70",
    "Water inlet fault on Miele washers.",
    "Miele W1 washers",
    ["WWD120", "WCR870"],
    [
      cause({
        id: "supply",
        name: "Tap / pressure",
        prior: 0.34,
        summary: "Inlet water missing.",
        difficulty: 1,
        time_minutes: 5,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: [],
        safety: "SAFE_USER_CHECK",
        fix: "Open the tap fully.",
      }),
      cause({
        id: "filter",
        name: "Inlet filter in AquaStop",
        prior: 0.36,
        summary: "Filter in the inlet valve dirty.",
        difficulty: 2,
        time_minutes: 20,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["pliers"],
        safety: "SAFE_USER_CHECK",
        fix: "Clean the inlet filter according to the user manual.",
      }),
      cause({
        id: "valve",
        name: "Inlet / AquaStop valve",
        prior: 0.3,
        summary: "Valve not opening.",
        difficulty: 3,
        time_minutes: 45,
        cost_eur_min: 40,
        cost_eur_max: 120,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Replace the AquaStop valve assembly. Do not bypass it.",
      }),
    ],
    44,
    ["not-filling"],
    [
      {
        id: "miele-f70",
        text: "Is the wall tap open and other taps in the room working?",
        why: "F70 is a timed inlet. Household water is checked first.",
        answers: [
          {
            id: "yes",
            label: "Yes",
            likelihoods: { supply: 0.2, filter: 0.8, valve: 0.75 },
          },
          {
            id: "no",
            label: "No water",
            likelihoods: { supply: 0.95, filter: 0.2, valve: 0.15 },
          },
        ],
      },
    ],
    "https://www.miele.com/en/m/service-3850.htm",
  ),
  profile(
    "Samsung",
    "samsung",
    "Fridge",
    "fridge",
    "5E",
    "Defrost / fridge sensor error on some Samsung French-door models (display 5E / 22E family). Treat model-specifically.",
    "Samsung French-door refrigerators — verify on the exact model sticker",
    ["RF28R7351SR"],
    [
      cause({
        id: "sensor",
        name: "Defrost or compartment sensor",
        prior: 0.45,
        summary: "Thermistor out of range.",
        difficulty: 4,
        time_minutes: 70,
        cost_eur_min: 15,
        cost_eur_max: 45,
        tools: ["multimeter"],
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Sealed-system adjacent electrical work.",
        fix: "Technician should measure thermistor resistance against the service chart.",
      }),
      cause({
        id: "board",
        name: "Control",
        prior: 0.25,
        summary: "Main or inverter board.",
        difficulty: 5,
        time_minutes: 90,
        cost_eur_min: 80,
        cost_eur_max: 250,
        tools: [],
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "High-voltage inverter.",
        fix: "Professional board diagnosis.",
      }),
      cause({
        id: "connection",
        name: "Harness",
        prior: 0.3,
        summary: "Loose connector after a move.",
        difficulty: 3,
        time_minutes: 40,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["screwdriver"],
        safety: "CAUTION",
        fix: "Reseat connectors with power unplugged.",
      }),
    ],
    36,
    ["not-cooling"],
    [
      {
        id: "fridge-5e",
        text: "Did this start after moving or unplugging the fridge?",
        why: "A recent move raises harness and sensor-connector probability.",
        answers: [
          {
            id: "yes",
            label: "Yes",
            likelihoods: { sensor: 0.4, board: 0.25, connection: 0.8 },
          },
          {
            id: "no",
            label: "No, it appeared in place",
            likelihoods: { sensor: 0.7, board: 0.55, connection: 0.25 },
          },
        ],
      },
    ],
    "https://www.samsung.com/us/support/",
  ),
  profile(
    "LG",
    "lg",
    "Dryer",
    "dryer",
    "d80",
    "Restricted airflow — the dryer is not exhausting enough air.",
    "LG electric dryers with d80/d80 diagnostic",
    ["DLE3600W", "RC90V9AV2W"],
    [
      cause({
        id: "lint",
        name: "Lint filter / cabinet lint",
        prior: 0.4,
        summary: "Filter clogged or lint behind it.",
        difficulty: 1,
        time_minutes: 10,
        cost_eur_min: 0,
        cost_eur_max: 0,
        tools: ["vacuum"],
        safety: "SAFE_USER_CHECK",
        fix: "Clean the filter every load. Vacuum the housing.",
      }),
      cause({
        id: "duct",
        name: "Exhaust duct crush or lint",
        prior: 0.4,
        summary: "Crushed foil duct or long run.",
        difficulty: 2,
        time_minutes: 30,
        cost_eur_min: 12,
        cost_eur_max: 40,
        tools: ["screwdriver", "vacuum"],
        safety: "SAFE_USER_CHECK",
        fix: "Use rigid or semi-rigid duct, keep the run short, clear lint.",
      }),
      cause({
        id: "thermostat",
        name: "Thermistor / cycling thermostat",
        prior: 0.2,
        summary: "False over-temp or sensor.",
        difficulty: 4,
        time_minutes: 60,
        cost_eur_min: 12,
        cost_eur_max: 40,
        tools: ["multimeter"],
        safety: "PROFESSIONAL_ONLY",
        blocked_reason: "Electric dryer mains.",
        fix: "Technician should test the exhaust thermistor. Unplug first.",
      }),
    ],
    55,
    ["not-drying", "takes-too-long"],
    [
      {
        id: "d80-air",
        text: "Is the outside exhaust flap opening with strong airflow?",
        why: "d80 is an airflow clock. Outside flap is the cheapest proof.",
        answers: [
          {
            id: "no",
            label: "Weak or no flap movement",
            likelihoods: { lint: 0.7, duct: 0.85, thermostat: 0.25 },
          },
          {
            id: "yes",
            label: "Strong exhaust",
            likelihoods: { lint: 0.25, duct: 0.2, thermostat: 0.75 },
          },
        ],
      },
    ],
    "https://www.lg.com/us/support",
  ),
];
