import type { ChargerProfile, DeviceProfile } from "./index";

function device(
  slug: string,
  name: string,
  brand: string,
  connector: DeviceProfile["connector"],
  min: number,
  max: number,
  demand: number,
  extras: Partial<DeviceProfile> = {},
): DeviceProfile {
  return {
    id: `dev:${slug}`,
    name,
    slug,
    brand,
    connector,
    min_watts: min,
    max_watts: max,
    pd_version: extras.pd_version ?? "PD 3.0",
    pps: extras.pps,
    epr: extras.epr,
    notes: extras.notes ?? `${name} published input envelope ${min}–${max} W.`,
    demand,
    tag: extras.tag ?? "MANUFACTURER_VERIFIED",
  };
}

function charger(
  slug: string,
  name: string,
  brand: string,
  watts: number,
  demand: number,
  ports: ChargerProfile["ports"],
  allocations: ChargerProfile["allocations"],
): ChargerProfile {
  return {
    id: `chg:${slug}`,
    name,
    slug,
    brand,
    total_watts: watts,
    pd_version: watts >= 140 ? "PD 3.1" : "PD 3.0",
    demand,
    tag: "MANUFACTURER_VERIFIED",
    ports,
    allocations,
  };
}

export const SCALE_DEVICES: DeviceProfile[] = [
  device("iphone-16-plus", "iPhone 16 Plus", "Apple", "USB-C", 5, 30, 88),
  device("iphone-16-pro-max", "iPhone 16 Pro Max", "Apple", "USB-C", 5, 45, 92),
  device("iphone-15-pro", "iPhone 15 Pro", "Apple", "USB-C", 5, 27, 86),
  device("iphone-15-plus", "iPhone 15 Plus", "Apple", "USB-C", 5, 20, 78),
  device("iphone-14-pro", "iPhone 14 Pro", "Apple", "Lightning", 5, 27, 80),
  device("iphone-13", "iPhone 13", "Apple", "Lightning", 5, 20, 76),
  device("iphone-se-2022", "iPhone SE (2022)", "Apple", "Lightning", 5, 20, 62),
  device("ipad-mini-7", "iPad mini (A17 Pro)", "Apple", "USB-C", 10, 20, 64),
  device("ipad-10", "iPad (10th generation)", "Apple", "USB-C", 10, 20, 66),
  device("macbook-air-13-m2", "MacBook Air 13-inch (M2)", "Apple", "USB-C", 30, 67, 82),
  device("macbook-pro-16-m3", "MacBook Pro 16-inch (M3)", "Apple", "USB-C", 96, 140, 80, { epr: true, pd_version: "PD 3.1" }),
  device("macbook-air-13-m4", "MacBook Air 13-inch (M4)", "Apple", "USB-C", 30, 70, 84),
  device("galaxy-s25", "Galaxy S25", "Samsung", "USB-C", 5, 25, 82, { pps: true }),
  device("galaxy-s25-ultra", "Galaxy S25 Ultra", "Samsung", "USB-C", 5, 45, 84, { pps: true }),
  device("galaxy-s23", "Galaxy S23", "Samsung", "USB-C", 5, 25, 74, { pps: true }),
  device("galaxy-s23-ultra", "Galaxy S23 Ultra", "Samsung", "USB-C", 5, 45, 76, { pps: true }),
  device("galaxy-a55", "Galaxy A55", "Samsung", "USB-C", 5, 25, 68, { pps: true }),
  device("galaxy-z-fold6", "Galaxy Z Fold6", "Samsung", "USB-C", 5, 25, 70, { pps: true }),
  device("galaxy-watch7", "Galaxy Watch7", "Samsung", "Watch", 5, 10, 50),
  device("pixel-9-pro", "Pixel 9 Pro", "Google", "USB-C", 5, 27, 78, { pps: true }),
  device("pixel-8-pro", "Pixel 8 Pro", "Google", "USB-C", 5, 30, 72, { pps: true }),
  device("pixel-7", "Pixel 7", "Google", "USB-C", 5, 20, 64, { pps: true }),
  device("pixel-tablet", "Pixel Tablet", "Google", "USB-C", 10, 15, 52),
  device("xiaomi-14", "Xiaomi 14", "Xiaomi", "USB-C", 5, 90, 70, { pps: true }),
  device("xiaomi-14-ultra", "Xiaomi 14 Ultra", "Xiaomi", "USB-C", 5, 90, 62, { pps: true }),
  device("oneplus-12", "OnePlus 12", "OnePlus", "USB-C", 5, 100, 68, { pps: true }),
  device("oneplus-13", "OnePlus 13", "OnePlus", "USB-C", 5, 100, 66, { pps: true }),
  device("nothing-phone-2", "Nothing Phone (2)", "Nothing", "USB-C", 5, 45, 58, { pps: true }),
  device("surface-laptop-7", "Surface Laptop 7", "Microsoft", "USB-C", 45, 65, 64),
  device("surface-pro-11", "Surface Pro 11", "Microsoft", "USB-C", 39, 60, 62),
  device("xps-13-9340", "Dell XPS 13 (9340)", "Dell", "USB-C", 45, 60, 60),
  device("thinkpad-t14s-g4", "ThinkPad T14s Gen 4", "Lenovo", "USB-C", 45, 65, 58),
  device("yoga-slim-7", "Yoga Slim 7", "Lenovo", "USB-C", 45, 65, 54),
  device("rog-ally", "ROG Ally", "ASUS", "USB-C", 30, 65, 70),
  device("legion-go", "Legion Go", "Lenovo", "USB-C", 45, 65, 64),
  device("switch-2", "Nintendo Switch 2", "Nintendo", "USB-C", 15, 60, 80),
  device("quest-3s", "Meta Quest 3S", "Meta", "USB-C", 5, 18, 58),
  device("airpods-4", "AirPods 4 (USB-C case)", "Apple", "USB-C", 5, 5, 56),
  device("airpods-max-usbc", "AirPods Max (USB-C)", "Apple", "USB-C", 5, 5, 52),
  device("pixel-buds-pro-2", "Pixel Buds Pro 2", "Google", "USB-C", 5, 5, 48),
  device("galaxy-buds3-pro", "Galaxy Buds3 Pro", "Samsung", "USB-C", 5, 5, 50),
  device("apple-watch-ultra-2", "Apple Watch Ultra 2", "Apple", "Watch", 5, 5, 60),
  device("kindle-colorsoft", "Kindle Colorsoft", "Amazon", "USB-C", 5, 5, 44),
  device("remarkable-2", "reMarkable 2", "reMarkable", "USB-C", 5, 10, 42),
  device("steam-deck-lcd", "Steam Deck LCD", "Valve", "USB-C", 15, 45, 70),
  device("mac-mini-m4", "Mac mini (M4)", "Apple", "USB-C", 70, 70, 58),
  device("ipad-pro-m2", "iPad Pro 12.9 (M2)", "Apple", "USB-C", 20, 45, 66),
  device("galaxy-tab-s10", "Galaxy Tab S10", "Samsung", "USB-C", 15, 45, 58, { pps: true }),
  device("pixel-9a", "Pixel 9a", "Google", "USB-C", 5, 23, 64, { pps: true }),
  device("iphone-12", "iPhone 12", "Apple", "Lightning", 5, 20, 70),
];

export const SCALE_CHARGERS: ChargerProfile[] = [
  charger("apple-5w", "Apple 5W USB-A", "Apple", 5, 50, [{ id: "a1", label: "A1", watts: 5, pdos: [{ volts: 5, amps: 1, watts: 5 }] }], [{ ports: ["a1"], watts: [5] }]),
  charger("samsung-25w", "Samsung 25W USB-C", "Samsung", 25, 80, [{ id: "c1", label: "C1", watts: 25, pdos: [{ volts: 9, amps: 2.77, watts: 25, pps: true }, { volts: 5, amps: 3, watts: 15 }] }], [{ ports: ["c1"], watts: [25] }]),
  charger("samsung-45w", "Samsung 45W USB-C", "Samsung", 45, 76, [{ id: "c1", label: "C1", watts: 45, pdos: [{ volts: 20, amps: 2.25, watts: 45, pps: true }, { volts: 15, amps: 3, watts: 45 }] }], [{ ports: ["c1"], watts: [45] }]),
  charger("google-30w", "Google 30W USB-C", "Google", 30, 70, [{ id: "c1", label: "C1", watts: 30, pdos: [{ volts: 15, amps: 2, watts: 30, pps: true }, { volts: 9, amps: 3, watts: 27 }] }], [{ ports: ["c1"], watts: [30] }]),
  charger("anker-30w", "Anker 30W Nano", "Anker", 30, 74, [{ id: "c1", label: "C1", watts: 30, pdos: [{ volts: 15, amps: 2, watts: 30 }, { volts: 9, amps: 3, watts: 27 }] }], [{ ports: ["c1"], watts: [30] }]),
  charger("anker-140w", "Anker 140W Prime", "Anker", 140, 72, [
    { id: "c1", label: "C1", watts: 140, pdos: [{ volts: 28, amps: 5, watts: 140 }, { volts: 20, amps: 5, watts: 100 }] },
    { id: "c2", label: "C2", watts: 100, pdos: [{ volts: 20, amps: 5, watts: 100 }] },
  ], [{ ports: ["c1"], watts: [140] }, { ports: ["c1", "c2"], watts: [100, 40] }]),
  charger("ugreen-65w", "UGREEN Nexode 65W", "UGREEN", 65, 70, [{ id: "c1", label: "C1", watts: 65, pdos: [{ volts: 20, amps: 3.25, watts: 65 }, { volts: 15, amps: 3, watts: 45 }] }], [{ ports: ["c1"], watts: [65] }]),
  charger("ugreen-145w", "UGREEN Nexode 145W 3C", "UGREEN", 145, 66, [
    { id: "c1", label: "C1", watts: 140, pdos: [{ volts: 28, amps: 5, watts: 140 }] },
    { id: "c2", label: "C2", watts: 65, pdos: [{ volts: 20, amps: 3.25, watts: 65 }] },
    { id: "c3", label: "C3", watts: 30, pdos: [{ volts: 15, amps: 2, watts: 30 }] },
  ], [{ ports: ["c1"], watts: [140] }, { ports: ["c1", "c2"], watts: [100, 45] }, { ports: ["c1", "c2", "c3"], watts: [65, 45, 30] }]),
  charger("belkin-67w", "Belkin BoostCharge 67W", "Belkin", 67, 64, [{ id: "c1", label: "C1", watts: 67, pdos: [{ volts: 20, amps: 3.35, watts: 67 }] }], [{ ports: ["c1"], watts: [67] }]),
  charger("belkin-65w-2c", "Belkin 65W 2C", "Belkin", 65, 62, [
    { id: "c1", label: "C1", watts: 65, pdos: [{ volts: 20, amps: 3.25, watts: 65 }] },
    { id: "c2", label: "C2", watts: 30, pdos: [{ volts: 15, amps: 2, watts: 30 }] },
  ], [{ ports: ["c1"], watts: [65] }, { ports: ["c1", "c2"], watts: [45, 20] }]),
  charger("baseus-100w", "Baseus GaN5 100W", "Baseus", 100, 60, [
    { id: "c1", label: "C1", watts: 100, pdos: [{ volts: 20, amps: 5, watts: 100 }] },
    { id: "c2", label: "C2", watts: 30, pdos: [{ volts: 15, amps: 2, watts: 30 }] },
  ], [{ ports: ["c1"], watts: [100] }, { ports: ["c1", "c2"], watts: [65, 30] }]),
  charger("baseus-65w", "Baseus 65W", "Baseus", 65, 58, [{ id: "c1", label: "C1", watts: 65, pdos: [{ volts: 20, amps: 3.25, watts: 65 }] }], [{ ports: ["c1"], watts: [65] }]),
  charger("apple-96w", "Apple 96W USB-C", "Apple", 96, 68, [{ id: "c1", label: "C1", watts: 96, pdos: [{ volts: 20, amps: 4.7, watts: 96 }] }], [{ ports: ["c1"], watts: [96] }]),
  charger("xiaomi-90w", "Xiaomi 90W HyperCharge", "Xiaomi", 90, 56, [{ id: "c1", label: "C1", watts: 90, pdos: [{ volts: 20, amps: 4.5, watts: 90, pps: true }] }], [{ ports: ["c1"], watts: [90] }]),
  charger("oneplus-100w", "OnePlus 100W SUPERVOOC", "OnePlus", 100, 54, [{ id: "c1", label: "C1", watts: 100, pdos: [{ volts: 20, amps: 5, watts: 100, pps: true }] }], [{ ports: ["c1"], watts: [100] }]),
  charger("anker-20w", "Anker 20W Nano", "Anker", 20, 78, [{ id: "c1", label: "C1", watts: 20, pdos: [{ volts: 9, amps: 2.22, watts: 20 }, { volts: 5, amps: 3, watts: 15 }] }], [{ ports: ["c1"], watts: [20] }]),
];
