import type { ChargerProfile, DeviceProfile } from "./index";

export const MORE_DEVICES: DeviceProfile[] = [
  { id: "dev:iphone-16-pro", name: "iPhone 16 Pro", slug: "iphone-16-pro", brand: "Apple", connector: "USB-C", min_watts: 5, max_watts: 45, pd_version: "PD 3.0", notes: "USB-C PD. Higher-wattage USB-C bricks can fill faster than the 20W cube.", demand: 94, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:iphone-14", name: "iPhone 14", slug: "iphone-14", brand: "Apple", connector: "Lightning", min_watts: 5, max_watts: 20, pd_version: "PD 3.0", notes: "Lightning PD up to about 20W. A USB-C-only brick needs a USB-C to Lightning cable.", demand: 82, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:mba-m3-15", name: "MacBook Air 15-inch (M3)", slug: "macbook-air-15-m3", brand: "Apple", connector: "USB-C", min_watts: 30, max_watts: 70, pd_version: "PD 3.0", notes: "Same PD envelope as the 13-inch M3 Air. 30W keeps it alive; 70W fills faster.", demand: 80, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:ipad-air-m2", name: "iPad Air (M2)", slug: "ipad-air-m2", brand: "Apple", connector: "USB-C", min_watts: 12, max_watts: 30, pd_version: "PD 3.0", notes: "Fast charge is a 30W-class PD brick, not a 5W phone cube.", demand: 68, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:pixel-9", name: "Pixel 9", slug: "pixel-9", brand: "Google", connector: "USB-C", min_watts: 5, max_watts: 27, pd_version: "PD 3.0", pps: true, notes: "PPS preferred. A PD-only 20W brick still charges.", demand: 76, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:s24-ultra", name: "Galaxy S24 Ultra", slug: "galaxy-s24-ultra", brand: "Samsung", connector: "USB-C", min_watts: 5, max_watts: 45, pd_version: "PD 3.0", pps: true, notes: "PPS Super Fast Charging up to 45W. A 25W PD-only brick is slower, not incompatible.", demand: 78, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:steam-deck-oled", name: "Steam Deck OLED", slug: "steam-deck-oled", brand: "Valve", connector: "USB-C", min_watts: 15, max_watts: 45, pd_version: "PD 3.0", notes: "Official 45W PD. Same class as LCD Deck; dock behaviour still varies.", demand: 74, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:switch-oled", name: "Nintendo Switch OLED", slug: "nintendo-switch-oled", brand: "Nintendo", connector: "USB-C", min_watts: 15, max_watts: 39, notes: "Official dock/charger is ~39W. Third-party 20–30W PD often works, slowly in handheld.", demand: 72, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:framework-13", name: "Framework Laptop 13", slug: "framework-13", brand: "Framework", connector: "USB-C", min_watts: 45, max_watts: 60, pd_version: "PD 3.0", notes: "60W USB-C PD is the published expansion-card / charger class.", demand: 62, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:quest-3", name: "Meta Quest 3", slug: "quest-3", brand: "Meta", connector: "USB-C", min_watts: 5, max_watts: 18, pd_version: "PD 3.0", notes: "Official ~18W USB-C. A laptop PD port will throttle down.", demand: 64, tag: "MANUFACTURER_VERIFIED" },
  { id: "dev:tab-s9", name: "Galaxy Tab S9", slug: "galaxy-tab-s9", brand: "Samsung", connector: "USB-C", min_watts: 15, max_watts: 45, pd_version: "PD 3.0", pps: true, notes: "45W Super Fast Charging with a PPS brick.", demand: 60, tag: "MANUFACTURER_VERIFIED" },
];

export const MORE_CHARGERS: ChargerProfile[] = [
  {
    id: "chg:apple-30w",
    name: "Apple 30W USB-C",
    slug: "apple-30w",
    brand: "Apple",
    total_watts: 30,
    pd_version: "PD 3.0",
    demand: 82,
    tag: "MANUFACTURER_VERIFIED",
    ports: [{ id: "c1", label: "C1", watts: 30, pdos: [{ volts: 20, amps: 1.5, watts: 30 }, { volts: 9, amps: 3, watts: 27 }] }],
    allocations: [{ ports: ["c1"], watts: [30] }],
  },
  {
    id: "chg:anker-45w",
    name: "Anker 45W USB-C (Nano class)",
    slug: "anker-45w",
    brand: "Anker",
    total_watts: 45,
    pd_version: "PD 3.0",
    demand: 78,
    tag: "MANUFACTURER_VERIFIED",
    ports: [{ id: "c1", label: "C1", watts: 45, pdos: [{ volts: 20, amps: 2.25, watts: 45 }, { volts: 15, amps: 3, watts: 45 }] }],
    allocations: [{ ports: ["c1"], watts: [45] }],
  },
  {
    id: "chg:ugreen-100w",
    name: "UGREEN Nexode 100W 2C",
    slug: "ugreen-100w",
    brand: "UGREEN",
    total_watts: 100,
    pd_version: "PD 3.0",
    demand: 74,
    tag: "MANUFACTURER_VERIFIED",
    ports: [
      { id: "c1", label: "C1", watts: 100, pdos: [{ volts: 20, amps: 5, watts: 100 }] },
      { id: "c2", label: "C2", watts: 30, pdos: [{ volts: 15, amps: 2, watts: 30 }] },
    ],
    allocations: [
      { ports: ["c1"], watts: [100] },
      { ports: ["c1", "c2"], watts: [65, 30] },
    ],
  },
  {
    id: "chg:apple-140w",
    name: "Apple 140W USB-C",
    slug: "apple-140w",
    brand: "Apple",
    total_watts: 140,
    pd_version: "PD 3.1",
    demand: 70,
    tag: "MANUFACTURER_VERIFIED",
    ports: [{ id: "c1", label: "C1", watts: 140, pdos: [{ volts: 28, amps: 5, watts: 140 }, { volts: 20, amps: 5, watts: 100 }] }],
    allocations: [{ ports: ["c1"], watts: [140] }],
  },
];

/** Curated search pairs. Obscure device×charger stays in the graph, not here. */
export const MORE_PAIRS: Array<[string, string]> = [
  ["iphone-16-pro", "apple-20w"],
  ["iphone-16-pro", "apple-30w"],
  ["iphone-16-pro", "anker-65w"],
  ["iphone-16-pro", "anker-100w-2c"],
  ["iphone-14", "apple-20w"],
  ["iphone-14", "apple-30w"],
  ["macbook-air-15-m3", "apple-70w"],
  ["macbook-air-15-m3", "anker-65w"],
  ["macbook-air-15-m3", "apple-30w"],
  ["ipad-air-m2", "apple-20w"],
  ["ipad-air-m2", "apple-30w"],
  ["pixel-9", "anker-65w"],
  ["pixel-9", "anker-45w"],
  ["galaxy-s24-ultra", "anker-65w"],
  ["galaxy-s24-ultra", "apple-30w"],
  ["steam-deck-oled", "anker-65w"],
  ["steam-deck-oled", "anker-45w"],
  ["nintendo-switch-oled", "apple-20w"],
  ["nintendo-switch-oled", "anker-45w"],
  ["framework-13", "anker-65w"],
  ["quest-3", "apple-20w"],
  ["galaxy-tab-s9", "anker-65w"],
  ["ipad-pro-m4", "anker-65w"],
  ["macbook-pro-14-m3", "anker-100w-2c"],
  ["macbook-pro-14-m3", "apple-140w"],
  ["iphone-16", "apple-30w"],
  ["iphone-15", "anker-65w"],
  ["galaxy-s24", "apple-20w"],
  ["pixel-8", "anker-45w"],
  ["steam-deck", "anker-45w"],
];
