import type { VehicleIdentity } from "./data";

function v(partial: VehicleIdentity): VehicleIdentity {
  return partial;
}

const oil = (spec: string, viscosity: string, capacity_liters: number) => ({
  spec,
  viscosity,
  capacity_liters,
  with_filter: capacity_liters > 0,
});

const evOil = oil("None (EV)", "n/a", 0);

const recall = (url: string) => [
  {
    id: "vin-portal",
    title: "Check the official recall portal by VIN",
    campaign: "VIN-specific",
    status: "CHECK" as const,
    source_url: url,
  },
];

const servicesIce = (oilSpec: string, cap: string, km = 15000) => [
  { id: "oil", name: "Engine oil & filter", interval_km: km, interval_months: 12, spec: oilSpec, capacity: cap },
  { id: "brakes", name: "Brake inspection", interval_km: 15000, interval_months: 12 },
  { id: "tyres", name: "Tyres", interval_km: 15000, interval_months: 12 },
  { id: "battery", name: "12V battery test", interval_km: 30000, interval_months: 24 },
  { id: "cabin", name: "Cabin filter", interval_km: 30000, interval_months: 24 },
];

const servicesEv = [
  { id: "tyres", name: "Tyre rotation / pressure", interval_km: 10000, interval_months: 6 },
  { id: "cabin", name: "Cabin filter", interval_km: 30000, interval_months: 24 },
  { id: "brake-fluid", name: "Brake fluid", interval_km: 40000, interval_months: 24, spec: "Confirm owner's manual" },
  { id: "battery", name: "12V / LV battery health", interval_km: 30000, interval_months: 24 },
];

export const MORE_VEHICLES: VehicleIdentity[] = [
  v({
    id: "veh:mercedes:c-class:w206:c220d",
    make: "Mercedes-Benz", make_slug: "mercedes", model: "C-Class", model_slug: "c-class",
    generation: "W206", generation_slug: "w206", variant: "C220d", variant_slug: "c220d",
    years: [2021, 2022, 2023, 2024], engine: "2.0 diesel", engine_code: "OM654",
    transmission: "9G-Tronic", market: ["EU"],
    oil: oil("MB 229.52 / 229.51", "5W-30", 6.0),
    tyres: { front: "225/45R18", rear: "245/40R18", pressure_bar_front: 2.4, pressure_bar_rear: 2.6 },
    battery: { type: "AGM", ah: 80 }, wipers: { driver_mm: 650, passenger_mm: 400 },
    services: servicesIce("MB 229.52 5W-30", "approx 6.0 L with filter", 25000),
    recalls: recall("https://www.mercedes-benz.com"),
    issues: [{ id: "om654-dpf", title: "DPF / short-trip diesel", severity: "MEDIUM", summary: "Urban diesels soot faster. Not a diagnosis from one warning.", when_to_stop: "If limp mode or a red temperature lamp appears, stop." }],
    fitment: [{ component_id: "oil-mb-229-52", component_name: "MB 229.52 5W-30", compatible: true, confidence: "HIGH", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "HIGH",
  }),
  v({
    id: "veh:audi:a4:b9:2-0-tdi",
    make: "Audi", make_slug: "audi", model: "A4", model_slug: "a4",
    generation: "B9", generation_slug: "b9", variant: "2.0 TDI", variant_slug: "2-0-tdi",
    years: [2016, 2017, 2018, 2019, 2020], engine: "2.0 TDI", engine_code: "EA288",
    transmission: "S tronic", market: ["EU"],
    oil: oil("VW 507.00", "5W-30", 4.7),
    tyres: { front: "225/50R17", rear: "225/50R17", pressure_bar_front: 2.3, pressure_bar_rear: 2.3 },
    battery: { type: "AGM", ah: 70 }, wipers: { driver_mm: 600, passenger_mm: 480 },
    services: servicesIce("VW 507.00 5W-30", "approx 4.7 L — confirm procedure"),
    recalls: recall("https://www.audi.com"),
    issues: [{ id: "timing-chain-note", title: "Do not assume a chain from a forum year", severity: "LOW", summary: "EA288 variants differ. We will not assign a timing-chain job from mileage alone.", when_to_stop: "Rattle at cold start plus a warning lamp: stop and scan." }],
    fitment: [{ component_id: "oil-507", component_name: "VW 507.00 5W-30", compatible: true, confidence: "HIGH", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "HIGH",
  }),
  v({
    id: "veh:peugeot:208:p21:1-2-puretech",
    make: "Peugeot", make_slug: "peugeot", model: "208", model_slug: "208",
    generation: "P21", generation_slug: "p21", variant: "1.2 PureTech", variant_slug: "1-2-puretech",
    years: [2020, 2021, 2022, 2023], engine: "1.2 turbo", engine_code: "EB2ADT",
    transmission: "6-speed / EAT8", market: ["EU"],
    oil: oil("PSA B71 2312 / ACEA C3", "0W-30", 3.5),
    tyres: { front: "195/55R16", rear: "195/55R16", pressure_bar_front: 2.4, pressure_bar_rear: 2.4 },
    battery: { type: "EFB", ah: 50 }, wipers: { driver_mm: 600, passenger_mm: 400 },
    services: servicesIce("0W-30 PSA spec", "about 3.5 L", 12000),
    recalls: recall("https://www.peugeot.com"),
    issues: [{ id: "belt-in-oil", title: "Wet belt — follow the official interval, not a blog", severity: "HIGH", summary: "PureTech wet belts are a known cost item. Interval is official, not inferred.", when_to_stop: "If the engine knocks or oil pressure warns, do not continue." }],
    fitment: [{ component_id: "oil-psa-0w30", component_name: "0W-30 PSA B71 2312 class", compatible: true, confidence: "MEDIUM", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "MEDIUM",
  }),
  v({
    id: "veh:renault:clio:v:1-0-tce",
    make: "Renault", make_slug: "renault", model: "Clio", model_slug: "clio",
    generation: "V", generation_slug: "5", variant: "1.0 TCe", variant_slug: "1-0-tce",
    years: [2019, 2020, 2021, 2022, 2023], engine: "1.0 turbo", engine_code: "H5D",
    transmission: "6-speed", market: ["EU"],
    oil: oil("RN17 / ACEA C3", "5W-30", 4.0),
    tyres: { front: "195/55R16", rear: "195/55R16", pressure_bar_front: 2.4, pressure_bar_rear: 2.2 },
    battery: { type: "EFB", ah: 50 }, wipers: { driver_mm: 600, passenger_mm: 400 },
    services: servicesIce("5W-30 RN17", "about 4.0 L"),
    recalls: recall("https://www.renault.com"),
    issues: [],
    fitment: [{ component_id: "oil-rn17", component_name: "5W-30 RN17", compatible: true, confidence: "MEDIUM", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "MEDIUM",
  }),
  v({
    id: "veh:hyundai:tucson:nx4:1-6-hybrid",
    make: "Hyundai", make_slug: "hyundai", model: "Tucson", model_slug: "tucson",
    generation: "NX4", generation_slug: "nx4", variant: "1.6 Hybrid", variant_slug: "1-6-hybrid",
    years: [2021, 2022, 2023, 2024], engine: "1.6 hybrid", engine_code: "G4FP",
    transmission: "6-speed auto", market: ["EU"],
    oil: oil("ACEA C5 / API SP", "0W-20", 4.8),
    tyres: { front: "235/55R18", rear: "235/55R18", pressure_bar_front: 2.5, pressure_bar_rear: 2.5 },
    battery: { type: "AGM", ah: 60 }, wipers: { driver_mm: 650, passenger_mm: 450 },
    services: servicesIce("0W-20", "about 4.8 L", 15000),
    recalls: recall("https://www.hyundai.com"),
    issues: [{ id: "12v-hybrid", title: "12V age on hybrids", severity: "MEDIUM", summary: "A weak 12V can refuse READY on a healthy hybrid.", when_to_stop: "If READY never stays on, have the 12V tested." }],
    fitment: [{ component_id: "oil-0w20-hy", component_name: "0W-20 API SP", compatible: true, confidence: "HIGH", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "HIGH",
  }),
  v({
    id: "veh:kia:sportage:nq5:1-6-hybrid",
    make: "Kia", make_slug: "kia", model: "Sportage", model_slug: "sportage",
    generation: "NQ5", generation_slug: "nq5", variant: "1.6 Hybrid", variant_slug: "1-6-hybrid",
    years: [2022, 2023, 2024], engine: "1.6 hybrid", engine_code: "G4FP",
    transmission: "6-speed auto", market: ["EU"],
    oil: oil("ACEA C5 / API SP", "0W-20", 4.8),
    tyres: { front: "235/55R18", rear: "235/55R18", pressure_bar_front: 2.5, pressure_bar_rear: 2.5 },
    battery: { type: "AGM", ah: 60 }, wipers: { driver_mm: 650, passenger_mm: 450 },
    services: servicesIce("0W-20", "about 4.8 L"),
    recalls: recall("https://www.kia.com"),
    issues: [],
    fitment: [{ component_id: "oil-0w20-kia", component_name: "0W-20 API SP", compatible: true, confidence: "HIGH", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "HIGH",
  }),
  v({
    id: "veh:volvo:xc60:t8:recharge",
    make: "Volvo", make_slug: "volvo", model: "XC60", model_slug: "xc60",
    generation: "SPA", generation_slug: "spa", variant: "T8 Recharge", variant_slug: "t8-recharge",
    years: [2022, 2023, 2024], engine: "2.0 plug-in hybrid", engine_code: "B420",
    transmission: "8-speed auto", market: ["EU"],
    oil: oil("Volvo VCC RBS0-2AE", "0W-20", 5.6),
    tyres: { front: "235/55R19", rear: "235/55R19", pressure_bar_front: 2.5, pressure_bar_rear: 2.5 },
    battery: { type: "AGM", ah: 70 }, wipers: { driver_mm: 650, passenger_mm: 500 },
    services: servicesIce("0W-20 VCC RBS0-2AE", "about 5.6 L", 15000),
    recalls: recall("https://www.volvocars.com"),
    issues: [],
    fitment: [{ component_id: "oil-volvo-0w20", component_name: "0W-20 Volvo spec", compatible: true, confidence: "HIGH", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "HIGH",
  }),
  v({
    id: "veh:tesla:model-y:juniper:lr",
    make: "Tesla", make_slug: "tesla", model: "Model Y", model_slug: "model-y",
    generation: "Juniper", generation_slug: "juniper", variant: "Long Range", variant_slug: "lr",
    years: [2025, 2026], engine: "Electric AWD", engine_code: "EV-AWD",
    transmission: "Dual motor", market: ["EU", "US"],
    oil: evOil,
    tyres: { front: "255/45R19", rear: "255/45R19", pressure_bar_front: 2.9, pressure_bar_rear: 2.9 },
    battery: { type: "12V lithium (vehicle-specific)", ah: 0 }, wipers: { driver_mm: 650, passenger_mm: 500 },
    services: servicesEv,
    recalls: recall("https://www.nhtsa.gov/recalls"),
    issues: [],
    fitment: [{ component_id: "tyre-255-45-19", component_name: "255/45R19", compatible: true, confidence: "MEDIUM", market: ["EU", "US"], source_id: "oem-handbook" }],
    confidence: "MEDIUM",
  }),
  v({
    id: "veh:vw:id3:e211:pro",
    make: "Volkswagen", make_slug: "volkswagen", model: "ID.3", model_slug: "id3",
    generation: "E21", generation_slug: "e21", variant: "Pro", variant_slug: "pro",
    years: [2021, 2022, 2023, 2024], engine: "Electric RWD", engine_code: "APP310",
    transmission: "Single-speed", market: ["EU"],
    oil: evOil,
    tyres: { front: "215/55R18", rear: "215/55R18", pressure_bar_front: 2.5, pressure_bar_rear: 2.5 },
    battery: { type: "12V AGM", ah: 50 }, wipers: { driver_mm: 600, passenger_mm: 450 },
    services: servicesEv,
    recalls: recall("https://www.vw.com/en/recall.html"),
    issues: [],
    fitment: [{ component_id: "tyre-215-55-18", component_name: "215/55R18", compatible: true, confidence: "MEDIUM", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "MEDIUM",
  }),
  v({
    id: "veh:toyota:rav4:xa50:hybrid",
    make: "Toyota", make_slug: "toyota", model: "RAV4", model_slug: "rav4",
    generation: "XA50", generation_slug: "xa50", variant: "2.5 Hybrid", variant_slug: "2-5-hybrid",
    years: [2019, 2020, 2021, 2022, 2023], engine: "2.5 hybrid", engine_code: "A25A-FXS",
    transmission: "e-CVT", market: ["EU", "US"],
    oil: oil("API SP / ILSAC GF-6", "0W-16 or 0W-20 as on the cap", 4.5),
    tyres: { front: "225/60R18", rear: "225/60R18", pressure_bar_front: 2.3, pressure_bar_rear: 2.3 },
    battery: { type: "EFB", ah: 60 }, wipers: { driver_mm: 650, passenger_mm: 450 },
    services: servicesIce("0W-16/0W-20 as specified", "about 4.5 L with filter"),
    recalls: recall("https://www.toyota.com/recall"),
    issues: [],
    fitment: [{ component_id: "oil-0w20-rav4", component_name: "0W-20 ILSAC GF-6", compatible: true, confidence: "HIGH", market: ["EU", "US"], source_id: "oem-handbook" }],
    confidence: "HIGH",
  }),
  v({
    id: "veh:bmw:x5:g05:30d",
    make: "BMW", make_slug: "bmw", model: "X5", model_slug: "x5",
    generation: "G05", generation_slug: "g05", variant: "xDrive30d", variant_slug: "30d-b57",
    years: [2019, 2020, 2021, 2022, 2023], engine: "3.0 diesel", engine_code: "B57D30",
    transmission: "8-speed automatic", market: ["EU"],
    oil: oil("BMW Longlife-04", "0W-30 or 5W-30 LL-04", 7.0),
    tyres: { front: "255/55R19", rear: "275/45R19", pressure_bar_front: 2.4, pressure_bar_rear: 2.6 },
    battery: { type: "AGM", ah: 90 }, wipers: { driver_mm: 650, passenger_mm: 500 },
    services: servicesIce("LL-04 0W-30/5W-30", "about 7.0 L with filter", 30000),
    recalls: recall("https://www.nhtsa.gov/recalls"),
    issues: [],
    fitment: [{ component_id: "oil-ll04-x5", component_name: "LL-04 5W-30", compatible: true, confidence: "HIGH", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "HIGH",
  }),
  v({
    id: "veh:ford:focus:mk4:1-0-ecoboost",
    make: "Ford", make_slug: "ford", model: "Focus", model_slug: "focus",
    generation: "Mk4", generation_slug: "mk4", variant: "1.0 EcoBoost", variant_slug: "1-0-ecoboost",
    years: [2019, 2020, 2021, 2022], engine: "1.0 turbo", engine_code: "M1DA",
    transmission: "6-speed", market: ["EU"],
    oil: oil("WSS-M2C948-B / Ford spec", "5W-20", 4.6),
    tyres: { front: "205/55R16", rear: "205/55R16", pressure_bar_front: 2.4, pressure_bar_rear: 2.2 },
    battery: { type: "EFB", ah: 50 }, wipers: { driver_mm: 650, passenger_mm: 400 },
    services: servicesIce("5W-20 Ford spec", "about 4.6 L"),
    recalls: recall("https://www.ford.com/support/recalls"),
    issues: [{ id: "wet-belt-ford", title: "Wet belt — official interval only", severity: "HIGH", summary: "Some 1.0 EcoBoost engines use a belt in oil. Follow Ford, not a generic 1.0 turbo article.", when_to_stop: "Knocking plus oil warning: stop." }],
    fitment: [{ component_id: "oil-5w20-ford", component_name: "5W-20 Ford spec", compatible: true, confidence: "MEDIUM", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "MEDIUM",
  }),
  v({
    id: "veh:vw:polo:aw:1-0-tsi",
    make: "Volkswagen", make_slug: "volkswagen", model: "Polo", model_slug: "polo",
    generation: "AW", generation_slug: "aw", variant: "1.0 TSI", variant_slug: "1-0-tsi",
    years: [2018, 2019, 2020, 2021, 2022], engine: "1.0 turbo petrol", engine_code: "DKLA",
    transmission: "6-speed", market: ["EU"],
    oil: oil("VW 508 00 / 504 00", "0W-20", 4.0),
    tyres: { front: "185/65R15", rear: "185/65R15", pressure_bar_front: 2.3, pressure_bar_rear: 2.1 },
    battery: { type: "EFB", ah: 44 }, wipers: { driver_mm: 600, passenger_mm: 380 },
    services: servicesIce("VW 508 00 0W-20", "about 4.0 L"),
    recalls: recall("https://www.volkswagen.co.uk/owners/recalls"),
    issues: [{ id: "timing-chain-3cyl", title: "Follow VW oil spec only", severity: "MEDIUM", summary: "1.0 TSI oil spec is not a generic 5W-30 supermarket fill.", when_to_stop: "Oil warning lamp: stop." }],
    fitment: [{ component_id: "oil-vw508", component_name: "VW 508 00 0W-20", compatible: true, confidence: "HIGH", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "HIGH",
  }),
  v({
    id: "veh:peugeot:308:t9:1-2-puretech",
    make: "Peugeot", make_slug: "peugeot", model: "308", model_slug: "308",
    generation: "T9", generation_slug: "t9", variant: "1.2 PureTech", variant_slug: "1-2-puretech",
    years: [2014, 2015, 2016, 2017, 2018, 2019, 2020], engine: "1.2 turbo petrol", engine_code: "EB2DT",
    transmission: "6-speed", market: ["EU"],
    oil: oil("PSA B71 2312 / ACEA C2", "0W-30", 3.5),
    tyres: { front: "205/55R16", rear: "205/55R16", pressure_bar_front: 2.4, pressure_bar_rear: 2.2 },
    battery: { type: "EFB", ah: 50 }, wipers: { driver_mm: 700, passenger_mm: 400 },
    services: servicesIce("PSA 0W-30 C2", "about 3.5 L"),
    recalls: recall("https://www.peugeot.co.uk/owners/recalls.html"),
    issues: [{ id: "wet-belt-psa", title: "Timing belt in oil — PSA interval", severity: "HIGH", summary: "Some PureTech engines use a wet belt. Use the official interval, not a shared '1.2 turbo' article.", when_to_stop: "Rattle plus oil pressure warning: stop." }],
    fitment: [{ component_id: "oil-psa-0w30", component_name: "PSA C2 0W-30", compatible: true, confidence: "MEDIUM", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "MEDIUM",
  }),
  v({
    id: "veh:nissan:qashqai:j12:1-3-digt",
    make: "Nissan", make_slug: "nissan", model: "Qashqai", model_slug: "qashqai",
    generation: "J12", generation_slug: "j12", variant: "1.3 DIG-T", variant_slug: "1-3-digt",
    years: [2021, 2022, 2023, 2024], engine: "1.3 turbo petrol", engine_code: "HR13DDT",
    transmission: "Xtronic", market: ["EU"],
    oil: oil("Nissan / ACEA C3", "5W-30", 5.4),
    tyres: { front: "215/60R17", rear: "215/60R17", pressure_bar_front: 2.4, pressure_bar_rear: 2.2 },
    battery: { type: "EFB", ah: 60 }, wipers: { driver_mm: 650, passenger_mm: 400 },
    services: servicesIce("5W-30 C3", "about 5.4 L"),
    recalls: recall("https://www.nissan.co.uk/owners/recalls.html"),
    issues: [],
    fitment: [{ component_id: "oil-nissan-5w30", component_name: "5W-30 C3", compatible: true, confidence: "MEDIUM", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "MEDIUM",
  }),
  v({
    id: "veh:honda:cr-v:rw:2-0-hybrid",
    make: "Honda", make_slug: "honda", model: "CR-V", model_slug: "cr-v",
    generation: "RW", generation_slug: "rw", variant: "2.0 Hybrid", variant_slug: "2-0-hybrid",
    years: [2018, 2019, 2020, 2021, 2022], engine: "2.0 Atkinson hybrid", engine_code: "LFB",
    transmission: "e-CVT", market: ["EU"],
    oil: oil("Honda / API SP", "0W-20", 4.0),
    tyres: { front: "235/60R18", rear: "235/60R18", pressure_bar_front: 2.3, pressure_bar_rear: 2.2 },
    battery: { type: "AGM", ah: 60 }, wipers: { driver_mm: 650, passenger_mm: 450 },
    services: servicesIce("0W-20 API SP", "about 4.0 L"),
    recalls: recall("https://www.honda.com/recalls"),
    issues: [],
    fitment: [{ component_id: "oil-0w20-honda-crv", component_name: "0W-20 API SP", compatible: true, confidence: "HIGH", market: ["EU"], source_id: "oem-handbook" }],
    confidence: "HIGH",
  }),
];
