import type { VehicleIdentity } from "./data";

const oil = (spec: string, viscosity: string, capacity_liters: number) => ({
  spec,
  viscosity,
  capacity_liters,
  with_filter: capacity_liters > 0,
});

const servicesIce = (oilSpec: string, cap: string, km = 15000) => [
  { id: "oil", name: "Engine oil & filter", interval_km: km, interval_months: 12, spec: oilSpec, capacity: cap },
  { id: "brakes", name: "Brake inspection", interval_km: 15000, interval_months: 12 },
  { id: "tyres", name: "Tyres", interval_km: 15000, interval_months: 12 },
  { id: "battery", name: "12V battery test", interval_km: 30000, interval_months: 24 },
  { id: "cabin", name: "Cabin filter", interval_km: 30000, interval_months: 24 },
];

const servicesEv = [
  { id: "tyres", name: "Tyre rotation / pressure", interval_km: 10000, interval_months: 6 },
  { id: "cabin", name: "Cabin filter", interval_km: 30000, interval_months: 24 },
  { id: "brake-fluid", name: "Brake fluid", interval_km: 40000, interval_months: 24, spec: "Confirm owner's manual" },
  { id: "battery", name: "12V / LV battery health", interval_km: 30000, interval_months: 24 },
];

type Seed = {
  make: string;
  make_slug: string;
  model: string;
  model_slug: string;
  gen: string;
  gen_slug: string;
  variant: string;
  variant_slug: string;
  years: number[];
  engine: string;
  engine_code: string;
  trans: string;
  spec: string;
  visc: string;
  cap: number;
  tyre: string;
  pf: number;
  pr: number;
  bat: string;
  ah: number;
  issue: string;
  summary: string;
  stop: string;
  url: string;
};

function vehicle(seed: Seed): VehicleIdentity {
  const ev = seed.cap === 0;
  return {
    id: `veh:${seed.make_slug}:${seed.model_slug}:${seed.gen_slug}:${seed.variant_slug}`,
    make: seed.make,
    make_slug: seed.make_slug,
    model: seed.model,
    model_slug: seed.model_slug,
    generation: seed.gen,
    generation_slug: seed.gen_slug,
    variant: seed.variant,
    variant_slug: seed.variant_slug,
    years: seed.years,
    engine: seed.engine,
    engine_code: seed.engine_code,
    transmission: seed.trans,
    market: ["EU"],
    oil: oil(seed.spec, seed.visc, seed.cap),
    tyres: { front: seed.tyre, rear: seed.tyre, pressure_bar_front: seed.pf, pressure_bar_rear: seed.pr },
    battery: { type: seed.bat, ah: seed.ah },
    wipers: { driver_mm: 650, passenger_mm: 400 },
    services: ev ? servicesEv : servicesIce(`${seed.visc} ${seed.spec}`, `about ${seed.cap} L`),
    recalls: [{ id: "vin-portal", title: "Check the official recall portal by VIN", campaign: "VIN-specific", status: "CHECK", source_url: seed.url }],
    issues: [
      {
        id: `${seed.engine_code.toLowerCase()}-note`,
        title: seed.issue,
        severity: "MEDIUM",
        summary: seed.summary,
        when_to_stop: seed.stop,
      },
    ],
    fitment: [
      {
        component_id: `oil-${seed.engine_code.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
        component_name: `${seed.visc} ${seed.spec}`,
        compatible: true,
        confidence: "MEDIUM",
        market: ["EU"],
        source_id: "oem-handbook",
      },
    ],
    confidence: "MEDIUM",
  };
}

const Y = (from: number, to: number) => Array.from({ length: to - from + 1 }, (_, i) => from + i);

const SEEDS: Seed[] = [
  { make: "BMW", make_slug: "bmw", model: "1 Series", model_slug: "1-series", gen: "F40", gen_slug: "f40", variant: "118i", variant_slug: "118i", years: Y(2019, 2024), engine: "1.5 petrol", engine_code: "B38B15", trans: "7-speed DCT", spec: "BMW Longlife-17 FE+", visc: "0W-20", cap: 4.3, tyre: "225/45R17", pf: 2.3, pr: 2.3, bat: "AGM", ah: 70, issue: "Oil spec is FE+, not LL-01", summary: "F40 118i uses a low-SAPS FE oil. A generic 5W-30 LL-01 fill is the wrong handbook row.", stop: "Oil pressure or drivetrain warning: stop and scan." , url: "https://www.bmw.com" },
  { make: "BMW", make_slug: "bmw", model: "5 Series", model_slug: "5-series", gen: "G30", gen_slug: "g30", variant: "520d", variant_slug: "520d-b47", years: Y(2017, 2023), engine: "2.0 diesel", engine_code: "B47D20O1", trans: "8-speed auto", spec: "BMW Longlife-04", visc: "0W-30", cap: 5.0, tyre: "245/45R18", pf: 2.4, pr: 2.6, bat: "AGM", ah: 90, issue: "Short-trip DPF load", summary: "Urban 520d cars soot faster. A single warning is not a DPF replacement diagnosis.", stop: "Limp mode or red temperature lamp: stop." , url: "https://www.bmw.com" },
  { make: "BMW", make_slug: "bmw", model: "X1", model_slug: "x1", gen: "U11", gen_slug: "u11", variant: "sDrive18d", variant_slug: "sdrive18d", years: Y(2022, 2025), engine: "2.0 diesel", engine_code: "B47D20U11", trans: "7-speed DCT", spec: "BMW Longlife-04", visc: "0W-30", cap: 5.0, tyre: "225/55R18", pf: 2.4, pr: 2.5, bat: "AGM", ah: 80, issue: "AdBlue / SCR is VIN-specific", summary: "U11 diesel aftertreatment is not interchangeable with F48 service notes.", stop: "AdBlue empty plus no-start warning: do not keep driving." , url: "https://www.bmw.com" },
  { make: "BMW", make_slug: "bmw", model: "X3", model_slug: "x3", gen: "G01", gen_slug: "g01", variant: "xDrive20d", variant_slug: "xdrive20d", years: Y(2018, 2024), engine: "2.0 diesel", engine_code: "B47D20X3", trans: "8-speed auto", spec: "BMW Longlife-04", visc: "5W-30", cap: 5.0, tyre: "245/50R19", pf: 2.4, pr: 2.6, bat: "AGM", ah: 90, issue: "Transfer-case oil is separate", summary: "xDrive service is not just engine oil. We do not invent a transfer-case interval from a blog.", stop: "Drivetrain warning plus binding on turns: stop and scan." , url: "https://www.bmw.com" },
  { make: "BMW", make_slug: "bmw", model: "X5", model_slug: "x5", gen: "G05", gen_slug: "g05", variant: "xDrive30d", variant_slug: "xdrive30d", years: Y(2019, 2024), engine: "3.0 diesel", engine_code: "B57D30", trans: "8-speed auto", spec: "BMW Longlife-04", visc: "0W-30", cap: 6.5, tyre: "275/45R20", pf: 2.5, pr: 2.7, bat: "AGM", ah: 105, issue: "Air-suspension warning is not a tyre issue", summary: "G05 height faults are not diagnosed from a tyre-pressure lamp.", stop: "Red suspension or brake lamp: stop." , url: "https://www.bmw.com" },
  { make: "Mercedes-Benz", make_slug: "mercedes", model: "A-Class", model_slug: "a-class", gen: "W177", gen_slug: "w177", variant: "A180", variant_slug: "a180", years: Y(2018, 2024), engine: "1.3 petrol", engine_code: "M282", trans: "7G-DCT", spec: "MB 229.71", visc: "0W-20", cap: 5.1, tyre: "205/55R17", pf: 2.4, pr: 2.2, bat: "AGM", ah: 70, issue: "MB 229.71 is not 229.5", summary: "M282 wants the low-viscosity MB spec on the cap, not a generic C3 5W-30.", stop: "Oil warning: stop." , url: "https://www.mercedes-benz.com" },
  { make: "Mercedes-Benz", make_slug: "mercedes", model: "E-Class", model_slug: "e-class", gen: "W213", gen_slug: "w213", variant: "E220d", variant_slug: "e220d", years: Y(2016, 2023), engine: "2.0 diesel", engine_code: "OM654E", trans: "9G-Tronic", spec: "MB 229.52", visc: "5W-30", cap: 6.0, tyre: "245/45R18", pf: 2.4, pr: 2.6, bat: "AGM", ah: 80, issue: "OM654 service is not OM651", summary: "Do not copy an older E-Class diesel interval onto W213.", stop: "Limp mode or coolant lamp: stop." , url: "https://www.mercedes-benz.com" },
  { make: "Mercedes-Benz", make_slug: "mercedes", model: "GLA", model_slug: "gla", gen: "H247", gen_slug: "h247", variant: "GLA200", variant_slug: "gla200", years: Y(2020, 2025), engine: "1.3 petrol", engine_code: "M282GLA", trans: "8G-DCT", spec: "MB 229.71", visc: "0W-20", cap: 5.1, tyre: "215/60R17", pf: 2.4, pr: 2.4, bat: "AGM", ah: 70, issue: "M282 wet-belt notes stay official", summary: "We will not invent a belt-year from a forum post.", stop: "Rattle plus oil lamp: stop." , url: "https://www.mercedes-benz.com" },
  { make: "Mercedes-Benz", make_slug: "mercedes", model: "GLC", model_slug: "glc", gen: "X253", gen_slug: "x253", variant: "GLC220d", variant_slug: "glc220d", years: Y(2016, 2022), engine: "2.0 diesel", engine_code: "OM654GLC", trans: "9G-Tronic", spec: "MB 229.52", visc: "5W-30", cap: 6.0, tyre: "235/60R18", pf: 2.4, pr: 2.6, bat: "AGM", ah: 80, issue: "Airmatic vs steel spring is VIN-specific", summary: "Suspension parts are not generation-generic.", stop: "Ride-height warning plus brake lamp: stop." , url: "https://www.mercedes-benz.com" },
  { make: "Audi", make_slug: "audi", model: "A3", model_slug: "a3", gen: "8Y", gen_slug: "8y", variant: "35 TDI", variant_slug: "35-tdi", years: Y(2020, 2025), engine: "2.0 TDI", engine_code: "EA288Evo", trans: "S tronic", spec: "VW 507.00", visc: "5W-30", cap: 5.5, tyre: "205/55R16", pf: 2.3, pr: 2.3, bat: "AGM", ah: 70, issue: "EA288 evo is not EA189", summary: "Oil and DPF notes from an older A3 TDI do not apply.", stop: "Glow-plug or limp lamp: stop and scan." , url: "https://www.audi.com" },
  { make: "Audi", make_slug: "audi", model: "A6", model_slug: "a6", gen: "C8", gen_slug: "c8", variant: "40 TDI", variant_slug: "40-tdi", years: Y(2018, 2024), engine: "2.0 TDI", engine_code: "EA288C8", trans: "S tronic", spec: "VW 507.00", visc: "0W-30", cap: 4.7, tyre: "225/55R18", pf: 2.4, pr: 2.5, bat: "AGM", ah: 80, issue: "MLB evo service is not C7", summary: "C8 intervals and oil spec are a different handbook row.", stop: "Oil pressure warning: stop." , url: "https://www.audi.com" },
  { make: "Audi", make_slug: "audi", model: "Q3", model_slug: "q3", gen: "F3", gen_slug: "f3", variant: "35 TFSI", variant_slug: "35-tfsi", years: Y(2018, 2024), engine: "1.5 TFSI", engine_code: "EA211Evo", trans: "S tronic", spec: "VW 508.00", visc: "0W-20", cap: 4.3, tyre: "215/55R17", pf: 2.4, pr: 2.4, bat: "EFB", ah: 60, issue: "ACT 1.5 is not 1.4 TSI", summary: "Cylinder-on-demand 1.5 TFSI oil is 508.00, not 502.00.", stop: "Misfire plus catalyst lamp: stop." , url: "https://www.audi.com" },
  { make: "Audi", make_slug: "audi", model: "Q5", model_slug: "q5", gen: "FY", gen_slug: "fy", variant: "40 TDI", variant_slug: "40-tdi", years: Y(2017, 2024), engine: "2.0 TDI", engine_code: "EA288Q5", trans: "S tronic", spec: "VW 507.00", visc: "5W-30", cap: 4.7, tyre: "235/60R18", pf: 2.4, pr: 2.5, bat: "AGM", ah: 80, issue: "Quattro clutch oil is separate", summary: "Haldex/rear clutch service is not engine oil.", stop: "AWD binding plus warning: scan, do not keep forcing it." , url: "https://www.audi.com" },
  { make: "Volkswagen", make_slug: "volkswagen", model: "Passat", model_slug: "passat", gen: "B8", gen_slug: "b8", variant: "2.0 TDI", variant_slug: "2-0-tdi", years: Y(2015, 2023), engine: "2.0 TDI", engine_code: "EA288B8", trans: "DSG", spec: "VW 507.00", visc: "5W-30", cap: 4.7, tyre: "215/55R17", pf: 2.3, pr: 2.3, bat: "EFB", ah: 70, issue: "DSG service is not engine oil", summary: "DQ250/DQ381 fluid is a separate official interval.", stop: "Gearbox limp: stop." , url: "https://www.volkswagen.com" },
  { make: "Volkswagen", make_slug: "volkswagen", model: "Tiguan", model_slug: "tiguan", gen: "AD1", gen_slug: "ad1", variant: "2.0 TDI", variant_slug: "2-0-tdi", years: Y(2016, 2023), engine: "2.0 TDI", engine_code: "EA288Tig", trans: "DSG", spec: "VW 507.00", visc: "5W-30", cap: 4.7, tyre: "215/65R17", pf: 2.4, pr: 2.4, bat: "AGM", ah: 70, issue: "4Motion Haldex is generation-specific", summary: "Do not copy a Mk1 Tiguan Haldex interval onto AD1.", stop: "AWD warning: scan." , url: "https://www.volkswagen.com" },
  { make: "Volkswagen", make_slug: "volkswagen", model: "Polo", model_slug: "polo", gen: "AW", gen_slug: "aw", variant: "1.0 TSI", variant_slug: "1-0-tsi", years: Y(2017, 2024), engine: "1.0 TSI", engine_code: "DKLA", trans: "6-speed", spec: "VW 508.00", visc: "0W-20", cap: 4.0, tyre: "185/65R15", pf: 2.2, pr: 2.2, bat: "EFB", ah: 44, issue: "3-cyl TSI oil is 508.00", summary: "A supermarket 5W-30 is the wrong Polo handbook row.", stop: "Oil lamp: stop." , url: "https://www.volkswagen.com" },
  { make: "Skoda", make_slug: "skoda", model: "Octavia", model_slug: "octavia", gen: "NX", gen_slug: "nx", variant: "2.0 TDI", variant_slug: "2-0-tdi", years: Y(2020, 2025), engine: "2.0 TDI", engine_code: "EA288NX", trans: "DSG", spec: "VW 507.00", visc: "5W-30", cap: 4.7, tyre: "205/55R17", pf: 2.3, pr: 2.3, bat: "AGM", ah: 70, issue: "MQB evo is not Mk3", summary: "Octavia NX oil and DSG notes differ from 5E.", stop: "DSG overheat or limp: stop." , url: "https://www.skoda-auto.com" },
  { make: "Skoda", make_slug: "skoda", model: "Superb", model_slug: "superb", gen: "3V", gen_slug: "3v", variant: "2.0 TDI", variant_slug: "2-0-tdi", years: Y(2015, 2023), engine: "2.0 TDI", engine_code: "EA288SB", trans: "DSG", spec: "VW 507.00", visc: "5W-30", cap: 4.7, tyre: "215/55R17", pf: 2.3, pr: 2.4, bat: "AGM", ah: 70, issue: "4x4 Haldex interval is official", summary: "We do not invent a Superb 4x4 fluid year.", stop: "AWD binding: scan." , url: "https://www.skoda-auto.com" },
  { make: "Skoda", make_slug: "skoda", model: "Kodiaq", model_slug: "kodiaq", gen: "NS7", gen_slug: "ns7", variant: "2.0 TDI", variant_slug: "2-0-tdi", years: Y(2017, 2023), engine: "2.0 TDI", engine_code: "EA288Kod", trans: "DSG", spec: "VW 507.00", visc: "5W-30", cap: 4.7, tyre: "235/55R18", pf: 2.4, pr: 2.5, bat: "AGM", ah: 80, issue: "7-seat load changes tyre pressure", summary: "Door-sticker pressures differ with load — we do not invent a third-row figure.", stop: "TPMS plus vibration: stop and inspect." , url: "https://www.skoda-auto.com" },
  { make: "Seat", make_slug: "seat", model: "Leon", model_slug: "leon", gen: "KL", gen_slug: "kl", variant: "1.5 TSI", variant_slug: "1-5-tsi", years: Y(2020, 2025), engine: "1.5 TSI", engine_code: "EA211Leon", trans: "6-speed", spec: "VW 508.00", visc: "0W-20", cap: 4.3, tyre: "205/55R16", pf: 2.3, pr: 2.3, bat: "EFB", ah: 59, issue: "ACT 1.5 oil is 508.00", summary: "Leon KL 1.5 TSI is not a 1.4 TSI 502.00 car.", stop: "Misfire lamp: scan, do not keep loading it." , url: "https://www.seat.com" },
  { make: "Seat", make_slug: "seat", model: "Ateca", model_slug: "ateca", gen: "KH7", gen_slug: "kh7", variant: "2.0 TDI", variant_slug: "2-0-tdi", years: Y(2016, 2023), engine: "2.0 TDI", engine_code: "EA288Ate", trans: "DSG", spec: "VW 507.00", visc: "5W-30", cap: 4.7, tyre: "215/55R17", pf: 2.4, pr: 2.4, bat: "EFB", ah: 70, issue: "4Drive Haldex is separate", summary: "Ateca 4Drive fluid is not engine oil.", stop: "AWD warning: scan." , url: "https://www.seat.com" },
  { make: "Toyota", make_slug: "toyota", model: "Yaris", model_slug: "yaris", gen: "XP210", gen_slug: "xp210", variant: "1.5 Hybrid", variant_slug: "1-5-hybrid", years: Y(2020, 2025), engine: "1.5 hybrid", engine_code: "M15A-FXE", trans: "e-CVT", spec: "API SP / ILSAC GF-6", visc: "0W-16", cap: 3.6, tyre: "185/65R15", pf: 2.5, pr: 2.5, bat: "EFB", ah: 45, issue: "0W-16 is on the cap", summary: "Yaris XP210 hybrid is not a 1NZ 5W-30 car.", stop: "READY never stays on: test the 12V first." , url: "https://www.toyota.com" },
  { make: "Toyota", make_slug: "toyota", model: "RAV4", model_slug: "rav4", gen: "XA50", gen_slug: "xa50", variant: "2.5 Hybrid", variant_slug: "2-5-hybrid", years: Y(2019, 2025), engine: "2.5 hybrid", engine_code: "A25A-FXS", trans: "e-CVT", spec: "API SP", visc: "0W-16", cap: 4.5, tyre: "225/60R18", pf: 2.3, pr: 2.3, bat: "AGM", ah: 60, issue: "AWD coupling fluid is separate", summary: "RAV4 Hybrid AWD is not a transfer-case copy from an older XA40.", stop: "AWD lamp plus binding: scan." , url: "https://www.toyota.com" },
  { make: "Toyota", make_slug: "toyota", model: "C-HR", model_slug: "c-hr", gen: "AX10", gen_slug: "ax10", variant: "1.8 Hybrid", variant_slug: "1-8-hybrid", years: Y(2016, 2023), engine: "1.8 hybrid", engine_code: "2ZR-FXE-CHR", trans: "e-CVT", spec: "API SN/SP", visc: "0W-20", cap: 4.2, tyre: "215/60R17", pf: 2.4, pr: 2.4, bat: "EFB", ah: 45, issue: "12V age on hybrids", summary: "A weak 12V can refuse READY on a healthy hybrid.", stop: "If READY never stays on, have the 12V tested." , url: "https://www.toyota.com" },
  { make: "Honda", make_slug: "honda", model: "Civic", model_slug: "civic", gen: "FL", gen_slug: "fl", variant: "1.5 VTEC", variant_slug: "1-5-vtec", years: Y(2022, 2025), engine: "1.5 turbo", engine_code: "L15C", trans: "CVT", spec: "Honda / API SP", visc: "0W-20", cap: 3.5, tyre: "215/50R17", pf: 2.3, pr: 2.3, bat: "EFB", ah: 50, issue: "1.5 VTEC dilution notes stay official", summary: "Short-trip oil dilution is a known watch item. We do not invent a drain-year.", stop: "Oil level overfull plus misfire: stop." , url: "https://www.honda.com" },
  { make: "Honda", make_slug: "honda", model: "Jazz", model_slug: "jazz", gen: "GR", gen_slug: "gr", variant: "1.5 Hybrid", variant_slug: "1-5-hybrid", years: Y(2020, 2025), engine: "1.5 hybrid", engine_code: "LEB-H4", trans: "e-CVT", spec: "Honda / API SP", visc: "0W-20", cap: 3.6, tyre: "185/60R15", pf: 2.3, pr: 2.3, bat: "EFB", ah: 40, issue: "e:HEV 12V first", summary: "A Jazz that will not READY is often 12V, not the traction pack.", stop: "No READY: test 12V before jump procedures." , url: "https://www.honda.com" },
  { make: "Mazda", make_slug: "mazda", model: "3", model_slug: "3", gen: "BP", gen_slug: "bp", variant: "2.0 Skyactiv-G", variant_slug: "2-0-skyactiv-g", years: Y(2019, 2025), engine: "2.0 petrol", engine_code: "PE-VPS", trans: "6-speed", spec: "Mazda / API SP", visc: "0W-20", cap: 4.2, tyre: "205/60R16", pf: 2.5, pr: 2.3, bat: "EFB", ah: 60, issue: "Skyactiv-X is a different row", summary: "This page is Skyactiv-G, not X. Compression-ignition notes do not apply.", stop: "Misfire plus catalyst lamp: stop." , url: "https://www.mazda.com" },
  { make: "Mazda", make_slug: "mazda", model: "CX-5", model_slug: "cx-5", gen: "KF", gen_slug: "kf", variant: "2.2 Skyactiv-D", variant_slug: "2-2-skyactiv-d", years: Y(2017, 2024), engine: "2.2 diesel", engine_code: "SH-VPTS", trans: "6-speed auto", spec: "Mazda / ACEA C3", visc: "5W-30", cap: 5.1, tyre: "225/55R19", pf: 2.5, pr: 2.5, bat: "EFB", ah: 70, issue: "DPF regen needs a real run", summary: "Urban CX-5 diesels need completed regen cycles. A single warning is not a DPF swap.", stop: "Limp plus exhaust overheat: stop." , url: "https://www.mazda.com" },
  { make: "Ford", make_slug: "ford", model: "Focus", model_slug: "focus", gen: "C519", gen_slug: "c519", variant: "1.0 EcoBoost", variant_slug: "1-0-ecoboost", years: Y(2018, 2024), engine: "1.0 turbo", engine_code: "B7DA", trans: "6-speed", spec: "WSS-M2C948-B", visc: "5W-20", cap: 4.6, tyre: "205/55R16", pf: 2.3, pr: 2.1, bat: "EFB", ah: 60, issue: "Wet belt interval is official", summary: "1.0 EcoBoost wet-belt years are handbook items, not a shared 'Ford 1.0' article.", stop: "Rattle plus oil pressure: stop." , url: "https://www.ford.com" },
  { make: "Ford", make_slug: "ford", model: "Puma", model_slug: "puma", gen: "J2K", gen_slug: "j2k", variant: "1.0 EcoBoost", variant_slug: "1-0-ecoboost", years: Y(2019, 2025), engine: "1.0 hybrid mild", engine_code: "B7DA-MHEV", trans: "6-speed", spec: "WSS-M2C948-B", visc: "5W-20", cap: 4.6, tyre: "205/55R17", pf: 2.4, pr: 2.2, bat: "AGM", ah: 70, issue: "mHEV 12V/48V is not a full hybrid pack", summary: "Puma mild-hybrid battery notes are not a RAV4 hybrid copy.", stop: "Auto-stop failure plus red battery: scan." , url: "https://www.ford.com" },
  { make: "Ford", make_slug: "ford", model: "Kuga", model_slug: "kuga", gen: "CX482", gen_slug: "cx482", variant: "2.5 PHEV", variant_slug: "2-5-phev", years: Y(2020, 2025), engine: "2.5 Atkinson PHEV", engine_code: "BG-PHEV", trans: "eCVT", spec: "WSS-M2C952-A1", visc: "0W-20", cap: 5.4, tyre: "225/60R18", pf: 2.4, pr: 2.4, bat: "AGM", ah: 50, issue: "PHEV coolant loops are dual", summary: "High-voltage coolant is not engine coolant. We do not invent a flush year.", stop: "Ready lamp off plus HV warning: stop." , url: "https://www.ford.com" },
  { make: "Hyundai", make_slug: "hyundai", model: "i30", model_slug: "i30", gen: "PD", gen_slug: "pd", variant: "1.0 T-GDi", variant_slug: "1-0-tgdi", years: Y(2017, 2024), engine: "1.0 turbo", engine_code: "G3LC", trans: "6-speed", spec: "ACEA C2 / API SP", visc: "0W-20", cap: 3.6, tyre: "195/65R15", pf: 2.3, pr: 2.1, bat: "EFB", ah: 60, issue: "Kappa 1.0 is not 1.6 GDi", summary: "Oil capacity and spec differ from the 1.6.", stop: "Oil lamp: stop." , url: "https://www.hyundai.com" },
  { make: "Hyundai", make_slug: "hyundai", model: "Ioniq 5", model_slug: "ioniq-5", gen: "NE", gen_slug: "ne", variant: "RWD 58 kWh", variant_slug: "rwd-58", years: Y(2021, 2025), engine: "electric", engine_code: "E-GMP-58", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "235/55R19", pf: 2.5, pr: 2.5, bat: "AGM", ah: 45, issue: "12V on E-GMP first", summary: "A 'dead' Ioniq 5 is often 12V isolation, not the traction pack.", stop: "No READY plus red HV: do not jump like an ICE." , url: "https://www.hyundai.com" },
  { make: "Kia", make_slug: "kia", model: "Ceed", model_slug: "ceed", gen: "CD", gen_slug: "cd", variant: "1.0 T-GDi", variant_slug: "1-0-tgdi", years: Y(2018, 2024), engine: "1.0 turbo", engine_code: "G3LE", trans: "6-speed", spec: "ACEA C2", visc: "0W-20", cap: 3.6, tyre: "195/65R15", pf: 2.3, pr: 2.1, bat: "EFB", ah: 60, issue: "Ceed CD is not JD", summary: "Service intervals from a 2014 Ceed do not apply.", stop: "Oil lamp: stop." , url: "https://www.kia.com" },
  { make: "Kia", make_slug: "kia", model: "Niro", model_slug: "niro", gen: "DE", gen_slug: "de", variant: "1.6 Hybrid", variant_slug: "1-6-hybrid", years: Y(2016, 2022), engine: "1.6 hybrid", engine_code: "G4LE", trans: "6-speed DCT", spec: "ACEA C5", visc: "0W-20", cap: 3.8, tyre: "205/60R16", pf: 2.4, pr: 2.4, bat: "AGM", ah: 60, issue: "Hybrid DCT fluid is official", summary: "Niro DCT oil is not a generic 'Hyundai 6DCT' blog interval.", stop: "READY never stays on: test 12V." , url: "https://www.kia.com" },
  { make: "Kia", make_slug: "kia", model: "EV6", model_slug: "ev6", gen: "CV", gen_slug: "cv", variant: "RWD 77 kWh", variant_slug: "rwd-77", years: Y(2021, 2025), engine: "electric", engine_code: "E-GMP-77", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "235/55R19", pf: 2.6, pr: 2.6, bat: "AGM", ah: 45, issue: "ICC / 12V first", summary: "EV6 no-start is often the 12V, not the 77 kWh pack.", stop: "No READY plus HV warning: do not treat as a jump-start ICE." , url: "https://www.kia.com" },
  { make: "Volvo", make_slug: "volvo", model: "XC40", model_slug: "xc40", gen: "X", gen_slug: "x", variant: "B4", variant_slug: "b4", years: Y(2020, 2025), engine: "2.0 mild hybrid", engine_code: "B420T", trans: "8-speed auto", spec: "Volvo VCC RBS0-2AE", visc: "0W-20", cap: 5.6, tyre: "235/55R18", pf: 2.4, pr: 2.4, bat: "AGM", ah: 70, issue: "SPA vs CMA oil is not shared blindly", summary: "XC40 CMA B4 is not an SPA T5 handbook copy.", stop: "Oil lamp: stop." , url: "https://www.volvocars.com" },
  { make: "Volvo", make_slug: "volvo", model: "XC60", model_slug: "xc60", gen: "SPA", gen_slug: "spa", variant: "B5", variant_slug: "b5", years: Y(2018, 2025), engine: "2.0 mild hybrid", engine_code: "B420T2", trans: "8-speed auto", spec: "Volvo VCC RBS0-2AE", visc: "0W-20", cap: 5.6, tyre: "235/60R18", pf: 2.4, pr: 2.5, bat: "AGM", ah: 80, issue: "Air-suspension option is VIN-specific", summary: "Not every XC60 has air springs.", stop: "Level warning plus brake lamp: stop." , url: "https://www.volvocars.com" },
  { make: "Volvo", make_slug: "volvo", model: "V60", model_slug: "v60", gen: "SPA", gen_slug: "spa-v60", variant: "B4", variant_slug: "b4", years: Y(2018, 2025), engine: "2.0 diesel mild", engine_code: "D420T", trans: "8-speed auto", spec: "Volvo VCC RBS0-2AE", visc: "0W-20", cap: 5.2, tyre: "215/55R17", pf: 2.4, pr: 2.4, bat: "AGM", ah: 70, issue: "Diesel B4 is not a D5", summary: "Capacity and aftertreatment differ from older D5 rows.", stop: "DPF limp: stop and scan." , url: "https://www.volvocars.com" },
  { make: "Peugeot", make_slug: "peugeot", model: "3008", model_slug: "3008", gen: "P84", gen_slug: "p84", variant: "1.2 PureTech", variant_slug: "1-2-puretech", years: Y(2016, 2023), engine: "1.2 turbo", engine_code: "EB2DTS", trans: "EAT8", spec: "PSA B71 2312", visc: "0W-30", cap: 3.5, tyre: "215/65R17", pf: 2.4, pr: 2.4, bat: "EFB", ah: 70, issue: "Wet belt — official interval", summary: "PureTech wet belts are a known cost item. Interval is official.", stop: "Knock plus oil pressure: stop." , url: "https://www.peugeot.com" },
  { make: "Peugeot", make_slug: "peugeot", model: "5008", model_slug: "5008", gen: "P87", gen_slug: "p87", variant: "1.5 BlueHDi", variant_slug: "1-5-bluehdi", years: Y(2017, 2023), engine: "1.5 diesel", engine_code: "DV5RC", trans: "EAT8", spec: "PSA B71 2290", visc: "0W-30", cap: 4.0, tyre: "215/65R17", pf: 2.5, pr: 2.5, bat: "EFB", ah: 70, issue: "AdBlue quality matters", summary: "A NOx lamp is not automatically an injector job.", stop: "Limp plus AdBlue empty: do not keep driving." , url: "https://www.peugeot.com" },
  { make: "Renault", make_slug: "renault", model: "Megane", model_slug: "megane", gen: "IV", gen_slug: "4", variant: "1.3 TCe", variant_slug: "1-3-tce", years: Y(2016, 2023), engine: "1.3 turbo", engine_code: "H5H", trans: "7-speed EDC", spec: "RN17", visc: "5W-30", cap: 4.6, tyre: "205/55R16", pf: 2.3, pr: 2.1, bat: "EFB", ah: 60, issue: "H5H is not H4Bt", summary: "Megane IV 1.3 TCe oil is RN17, not an older 1.2 TCe row.", stop: "Oil lamp: stop." , url: "https://www.renault.com" },
  { make: "Renault", make_slug: "renault", model: "Captur", model_slug: "captur", gen: "II", gen_slug: "2", variant: "1.0 TCe", variant_slug: "1-0-tce", years: Y(2020, 2025), engine: "1.0 turbo", engine_code: "H4D", trans: "6-speed", spec: "RN17", visc: "5W-30", cap: 4.0, tyre: "205/60R16", pf: 2.3, pr: 2.1, bat: "EFB", ah: 50, issue: "Captur II is not Captur I", summary: "Service and oil spec changed with the CMF-B platform.", stop: "Oil lamp: stop." , url: "https://www.renault.com" },
  { make: "Citroen", make_slug: "citroen", model: "C3", model_slug: "c3", gen: "CC21", gen_slug: "cc21", variant: "1.2 PureTech", variant_slug: "1-2-puretech", years: Y(2016, 2023), engine: "1.2 turbo", engine_code: "EB2DT-C3", trans: "6-speed", spec: "PSA B71 2312", visc: "0W-30", cap: 3.5, tyre: "185/65R15", pf: 2.3, pr: 2.1, bat: "EFB", ah: 50, issue: "Wet belt — official interval", summary: "Same PureTech family as 208. Interval is official, not a blog year.", stop: "Rattle plus oil pressure: stop." , url: "https://www.citroen.com" },
  { make: "Citroen", make_slug: "citroen", model: "C4", model_slug: "c4", gen: "C41", gen_slug: "c41", variant: "1.2 PureTech", variant_slug: "1-2-puretech", years: Y(2020, 2025), engine: "1.2 turbo", engine_code: "EB2DTS-C4", trans: "EAT8", spec: "PSA B71 2312", visc: "0W-30", cap: 3.5, tyre: "195/60R18", pf: 2.4, pr: 2.2, bat: "EFB", ah: 60, issue: "C41 is not B7 C4", summary: "Do not copy a 2012 C4 service schedule.", stop: "Oil lamp: stop." , url: "https://www.citroen.com" },
  { make: "Dacia", make_slug: "dacia", model: "Duster", model_slug: "duster", gen: "HM", gen_slug: "hm", variant: "1.5 Blue dCi", variant_slug: "1-5-bluedci", years: Y(2018, 2023), engine: "1.5 diesel", engine_code: "K9K", trans: "6-speed", spec: "RN17 / ACEA C3", visc: "5W-30", cap: 4.8, tyre: "215/65R16", pf: 2.2, pr: 2.2, bat: "flooded", ah: 70, issue: "4x4 transfer oil is separate", summary: "Duster 4x4 fluid is not engine oil.", stop: "4x4 lamp plus binding: scan." , url: "https://www.dacia.com" },
  { make: "Dacia", make_slug: "dacia", model: "Sandero", model_slug: "sandero", gen: "DJF", gen_slug: "djf", variant: "1.0 TCe", variant_slug: "1-0-tce", years: Y(2020, 2025), engine: "1.0 turbo", engine_code: "H4D-S", trans: "6-speed", spec: "RN17", visc: "5W-30", cap: 4.0, tyre: "185/65R15", pf: 2.2, pr: 2.0, bat: "flooded", ah: 50, issue: "Sandero III is CMF-B", summary: "Older Sandero II oil notes do not apply.", stop: "Oil lamp: stop." , url: "https://www.dacia.com" },
  { make: "Opel", make_slug: "opel", model: "Corsa", model_slug: "corsa", gen: "F", gen_slug: "f", variant: "1.2 Turbo", variant_slug: "1-2-turbo", years: Y(2019, 2025), engine: "1.2 turbo", engine_code: "EB2ADTD", trans: "8-speed auto", spec: "Opel / PSA B71 2312", visc: "0W-30", cap: 3.5, tyre: "185/65R15", pf: 2.3, pr: 2.1, bat: "EFB", ah: 50, issue: "Corsa F is PSA-based", summary: "Do not use a Corsa D 1.2 oil row.", stop: "Oil lamp: stop." , url: "https://www.opel.com" },
  { make: "Opel", make_slug: "opel", model: "Astra", model_slug: "astra", gen: "L", gen_slug: "l", variant: "1.2 Turbo", variant_slug: "1-2-turbo", years: Y(2021, 2025), engine: "1.2 turbo", engine_code: "EB2DTS-A", trans: "8-speed auto", spec: "Opel / PSA B71 2312", visc: "0W-30", cap: 3.5, tyre: "205/55R16", pf: 2.4, pr: 2.2, bat: "EFB", ah: 60, issue: "Astra L is not K", summary: "EMP2 / PSA oil spec replaced the older GM row.", stop: "Oil lamp: stop." , url: "https://www.opel.com" },
  { make: "Fiat", make_slug: "fiat", model: "500", model_slug: "500", gen: "312", gen_slug: "312", variant: "1.2 8V", variant_slug: "1-2-8v", years: Y(2015, 2023), engine: "1.2 petrol", engine_code: "169A4", trans: "5-speed", spec: "Fiat 9.55535-S1", visc: "5W-40", cap: 2.8, tyre: "175/65R14", pf: 2.2, pr: 2.0, bat: "flooded", ah: 40, issue: "TwinAir is a different page", summary: "This row is the 1.2 8V, not the 0.9 TwinAir.", stop: "Overheat lamp: stop." , url: "https://www.fiat.com" },
  { make: "Fiat", make_slug: "fiat", model: "Panda", model_slug: "panda", gen: "319", gen_slug: "319", variant: "1.0 Hybrid", variant_slug: "1-0-hybrid", years: Y(2020, 2025), engine: "1.0 mild hybrid", engine_code: "FIREFLY", trans: "6-speed", spec: "Fiat 9.55535-GS1", visc: "0W-20", cap: 3.2, tyre: "175/65R14", pf: 2.2, pr: 2.0, bat: "AGM", ah: 50, issue: "mHEV BSG is not a full hybrid", summary: "Panda Hybrid 12V/BSG notes are not a Toyota hybrid copy.", stop: "Auto-stop plus red battery: scan." , url: "https://www.fiat.com" },
  { make: "Jeep", make_slug: "jeep", model: "Compass", model_slug: "compass", gen: "MP", gen_slug: "mp", variant: "1.6 Multijet", variant_slug: "1-6-multijet", years: Y(2017, 2023), engine: "1.6 diesel", engine_code: "55260384", trans: "6-speed", spec: "Fiat 9.55535-DS1", visc: "0W-30", cap: 4.2, tyre: "215/60R17", pf: 2.3, pr: 2.3, bat: "EFB", ah: 70, issue: "4x4 Low is not always fitted", summary: "Compass 4x2 vs 4x4 service differs. Check the VIN build.", stop: "4x4 lamp plus binding: scan." , url: "https://www.jeep.com" },
  { make: "Mini", make_slug: "mini", model: "Cooper", model_slug: "cooper", gen: "F56", gen_slug: "f56", variant: "Cooper", variant_slug: "cooper", years: Y(2014, 2023), engine: "1.5 petrol", engine_code: "B38A15A", trans: "6-speed", spec: "BMW Longlife-01 FE / 17 FE+", visc: "0W-20", cap: 4.3, tyre: "195/55R16", pf: 2.4, pr: 2.2, bat: "AGM", ah: 70, issue: "B38 oil is FE, not LL-01 5W-30", summary: "F56 Cooper is not an R56 Prince handbook copy.", stop: "Oil lamp: stop." , url: "https://www.mini.com" },
  { make: "Tesla", make_slug: "tesla", model: "Model 3", model_slug: "model-3", gen: "Highland", gen_slug: "highland", variant: "RWD", variant_slug: "rwd", years: Y(2023, 2025), engine: "electric", engine_code: "M3-RWD-H", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "235/45R18", pf: 2.9, pr: 2.9, bat: "12V Li-ion", ah: 6, issue: "12V lithium first", summary: "A 'dead' Model 3 is often 12V, not the traction pack. Pressures are door-sticker, not a forum PSI.", stop: "No READY plus red HV: do not jump like an ICE." , url: "https://www.tesla.com" },
  { make: "Tesla", make_slug: "tesla", model: "Model Y", model_slug: "model-y", gen: "Juniper", gen_slug: "juniper", variant: "RWD", variant_slug: "rwd", years: Y(2025, 2026), engine: "electric", engine_code: "MY-RWD-J", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "255/45R19", pf: 2.9, pr: 2.9, bat: "12V Li-ion", ah: 6, issue: "Door-sticker pressures only", summary: "Model Y load and wheel size change PSI. We do not invent a third-row figure.", stop: "TPMS plus vibration: inspect before a long trip." , url: "https://www.tesla.com" },
  { make: "Nissan", make_slug: "nissan", model: "Juke", model_slug: "juke", gen: "F16", gen_slug: "f16", variant: "1.0 DIG-T", variant_slug: "1-0-digt", years: Y(2019, 2025), engine: "1.0 turbo", engine_code: "HR10DDT", trans: "7-speed DCT", spec: "Nissan / ACEA C3", visc: "5W-30", cap: 4.1, tyre: "215/55R17", pf: 2.3, pr: 2.1, bat: "EFB", ah: 60, issue: "F16 is not F15", summary: "Juke F16 1.0 DIG-T is not the old 1.6 DIG-T row.", stop: "Oil lamp: stop." , url: "https://www.nissan-global.com" },
  { make: "Suzuki", make_slug: "suzuki", model: "Vitara", model_slug: "vitara", gen: "LY", gen_slug: "ly", variant: "1.4 Boosterjet", variant_slug: "1-4-boosterjet", years: Y(2015, 2023), engine: "1.4 turbo", engine_code: "K14C", trans: "6-speed", spec: "Suzuki / API SN", visc: "0W-20", cap: 3.9, tyre: "215/60R16", pf: 2.2, pr: 2.2, bat: "EFB", ah: 50, issue: "AllGrip is not a transfer-case copy", summary: "Vitara AllGrip modes have their own fluid notes.", stop: "4x4 lamp: scan." , url: "https://www.suzuki.com" },
  { make: "Alfa Romeo", make_slug: "alfa", model: "Giulia", model_slug: "giulia", gen: "952", gen_slug: "952", variant: "2.2 Diesel", variant_slug: "2-2-diesel", years: Y(2016, 2023), engine: "2.2 diesel", engine_code: "55268542", trans: "8-speed auto", spec: "Fiat 9.55535-DS1", visc: "0W-30", cap: 4.7, tyre: "225/50R17", pf: 2.3, pr: 2.3, bat: "AGM", ah: 70, issue: "Giulia diesel is not a 2.0 petrol", summary: "Oil and DPF notes from a Quadrifoglio do not apply.", stop: "Limp plus DPF: stop." , url: "https://www.alfaromeo.com" },
  { make: "Land Rover", make_slug: "landrover", model: "Discovery Sport", model_slug: "discovery-sport", gen: "L550", gen_slug: "l550", variant: "D165", variant_slug: "d165", years: Y(2020, 2025), engine: "2.0 diesel", engine_code: "AJ200D", trans: "9-speed auto", spec: "Land Rover STJLR.03.5007", visc: "0W-20", cap: 6.5, tyre: "235/60R18", pf: 2.4, pr: 2.4, bat: "AGM", ah: 90, issue: "Ingenium D165 is not Td4 2.2", summary: "Do not copy a 2015 Discovery Sport oil row onto AJ200D.", stop: "Coolant or oil lamp: stop." , url: "https://www.landrover.com" },
  { make: "Land Rover", make_slug: "landrover", model: "Range Rover Evoque", model_slug: "evoque", gen: "L551", gen_slug: "l551", variant: "D200", variant_slug: "d200", years: Y(2019, 2025), engine: "2.0 diesel", engine_code: "AJ200D-E", trans: "9-speed auto", spec: "Land Rover STJLR.03.5007", visc: "0W-20", cap: 6.5, tyre: "235/60R18", pf: 2.4, pr: 2.4, bat: "AGM", ah: 90, issue: "Air-suspension option is VIN-specific", summary: "Not every Evoque L551 has air springs.", stop: "Level warning: stop if brake lamp is also on." , url: "https://www.landrover.com" },
  { make: "BMW", make_slug: "bmw", model: "3 Series", model_slug: "3-series", gen: "G20", gen_slug: "g20-330e", variant: "330e", variant_slug: "330e", years: Y(2019, 2024), engine: "2.0 PHEV", engine_code: "B48B20PHEV", trans: "8-speed auto", spec: "BMW Longlife-17 FE+", visc: "0W-20", cap: 5.3, tyre: "225/50R17", pf: 2.4, pr: 2.6, bat: "AGM", ah: 70, issue: "PHEV coolant is not engine-only", summary: "330e has a high-voltage loop. Do not treat it as a 320d oil page.", stop: "READY off plus HV warning: stop." , url: "https://www.bmw.com" },
  { make: "BMW", make_slug: "bmw", model: "iX", model_slug: "ix", gen: "I20", gen_slug: "i20", variant: "xDrive40", variant_slug: "xdrive40", years: Y(2021, 2025), engine: "electric", engine_code: "I20-40", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "255/50R21", pf: 2.5, pr: 2.7, bat: "AGM", ah: 50, issue: "12V first on iX", summary: "A silent iX is often 12V isolation, not the traction pack.", stop: "No READY plus red HV: do not jump like an ICE." , url: "https://www.bmw.com" },
  { make: "Mercedes-Benz", make_slug: "mercedes", model: "C-Class", model_slug: "c-class", gen: "W206", gen_slug: "w206", variant: "C220d", variant_slug: "c220d", years: Y(2021, 2025), engine: "2.0 diesel", engine_code: "OM654M", trans: "9G-Tronic", spec: "MB 229.52", visc: "0W-20", cap: 6.0, tyre: "225/50R17", pf: 2.4, pr: 2.5, bat: "AGM", ah: 80, issue: "W206 is not W205", summary: "Do not copy a 2016 C-Class oil row onto W206.", stop: "Oil or coolant lamp: stop." , url: "https://www.mercedes-benz.com" },
  { make: "Mercedes-Benz", make_slug: "mercedes", model: "EQB", model_slug: "eqb", gen: "X243", gen_slug: "x243", variant: "EQB 300", variant_slug: "eqb-300", years: Y(2021, 2025), engine: "electric", engine_code: "EQB-300", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "235/50R19", pf: 2.5, pr: 2.5, bat: "AGM", ah: 45, issue: "12V / ICCB first", summary: "EQB no-start is often 12V, not the HV pack.", stop: "No READY plus HV warning: stop." , url: "https://www.mercedes-benz.com" },
  { make: "Audi", make_slug: "audi", model: "A4", model_slug: "a4", gen: "B9", gen_slug: "b9", variant: "40 TDI", variant_slug: "40-tdi", years: Y(2016, 2023), engine: "2.0 TDI", engine_code: "EA288B9", trans: "S tronic", spec: "VW 507.00", visc: "5W-30", cap: 4.7, tyre: "225/50R17", pf: 2.3, pr: 2.3, bat: "AGM", ah: 80, issue: "B9 is not B8", summary: "MLB evo oil and DSG notes differ from B8.", stop: "Oil lamp: stop." , url: "https://www.audi.com" },
  { make: "Audi", make_slug: "audi", model: "Q7", model_slug: "q7", gen: "4M", gen_slug: "4m", variant: "45 TDI", variant_slug: "45-tdi", years: Y(2015, 2023), engine: "3.0 TDI", engine_code: "EA897", trans: "Tiptronic", spec: "VW 507.00", visc: "0W-30", cap: 6.1, tyre: "255/55R19", pf: 2.5, pr: 2.7, bat: "AGM", ah: 105, issue: "Air-suspension is optional", summary: "Not every Q7 4M has air springs.", stop: "Level warning plus brake lamp: stop." , url: "https://www.audi.com" },
  { make: "Volkswagen", make_slug: "volkswagen", model: "Golf", model_slug: "golf", gen: "Mk8", gen_slug: "mk8", variant: "1.5 TSI", variant_slug: "1-5-tsi", years: Y(2020, 2025), engine: "1.5 TSI", engine_code: "EA211EvoG", trans: "DSG", spec: "VW 508.00", visc: "0W-20", cap: 4.3, tyre: "205/55R16", pf: 2.3, pr: 2.3, bat: "EFB", ah: 59, issue: "ACT 1.5 oil is 508.00", summary: "Golf 8 1.5 TSI is not a Mk7 1.4 TSI 502.00 car.", stop: "Misfire lamp: scan." , url: "https://www.volkswagen.com" },
  { make: "Volkswagen", make_slug: "volkswagen", model: "ID.3", model_slug: "id3", gen: "E11", gen_slug: "e11", variant: "Pro 58 kWh", variant_slug: "pro-58", years: Y(2020, 2025), engine: "electric", engine_code: "APP310-58", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "215/55R18", pf: 2.5, pr: 2.5, bat: "AGM", ah: 40, issue: "12V isolation first", summary: "ID.3 brick is often 12V, not the MEB pack.", stop: "No READY plus HV: do not jump like an ICE." , url: "https://www.volkswagen.com" },
  { make: "Toyota", make_slug: "toyota", model: "Prius", model_slug: "prius", gen: "XW60", gen_slug: "xw60", variant: "2.0 Hybrid", variant_slug: "2-0-hybrid", years: Y(2023, 2026), engine: "2.0 hybrid", engine_code: "M20A-FXS", trans: "e-CVT", spec: "API SP", visc: "0W-16", cap: 4.3, tyre: "195/50R19", pf: 2.5, pr: 2.5, bat: "AGM", ah: 45, issue: "XW60 is not XW30", summary: "Do not copy a 2010 Prius oil row onto M20A-FXS.", stop: "READY never stays on: test 12V." , url: "https://www.toyota.com" },
  { make: "Toyota", make_slug: "toyota", model: "Camry", model_slug: "camry", gen: "XV70", gen_slug: "xv70", variant: "2.5 Hybrid", variant_slug: "2-5-hybrid", years: Y(2018, 2024), engine: "2.5 hybrid", engine_code: "A25A-FXS-C", trans: "e-CVT", spec: "API SP", visc: "0W-16", cap: 4.5, tyre: "215/55R17", pf: 2.3, pr: 2.3, bat: "AGM", ah: 60, issue: "0W-16 is on the cap", summary: "Camry XV70 hybrid is not a 2AR 0W-20 copy from an older petrol.", stop: "READY never stays on: test 12V." , url: "https://www.toyota.com" },
  { make: "Honda", make_slug: "honda", model: "CR-V", model_slug: "cr-v", gen: "RW", gen_slug: "rw", variant: "2.0 Hybrid", variant_slug: "2-0-hybrid", years: Y(2018, 2022), engine: "2.0 hybrid", engine_code: "LFB1", trans: "e-CVT", spec: "Honda / API SP", visc: "0W-20", cap: 4.0, tyre: "235/60R18", pf: 2.3, pr: 2.3, bat: "AGM", ah: 60, issue: "i-MMD 12V first", summary: "A CR-V that will not READY is often 12V.", stop: "No READY: test 12V." , url: "https://www.honda.com" },
  { make: "Ford", make_slug: "ford", model: "Fiesta", model_slug: "fiesta", gen: "B479", gen_slug: "b479", variant: "1.0 EcoBoost", variant_slug: "1-0-ecoboost", years: Y(2017, 2023), engine: "1.0 turbo", engine_code: "B7DA-F", trans: "6-speed", spec: "WSS-M2C948-B", visc: "5W-20", cap: 4.6, tyre: "195/55R16", pf: 2.3, pr: 2.1, bat: "EFB", ah: 50, issue: "Wet belt interval is official", summary: "Fiesta 1.0 EcoBoost wet-belt years are handbook items.", stop: "Rattle plus oil pressure: stop." , url: "https://www.ford.com" },
  { make: "Ford", make_slug: "ford", model: "Mustang Mach-E", model_slug: "mach-e", gen: "CX727", gen_slug: "cx727", variant: "RWD 75 kWh", variant_slug: "rwd-75", years: Y(2021, 2025), engine: "electric", engine_code: "MACH-E-75", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "225/55R19", pf: 2.6, pr: 2.6, bat: "AGM", ah: 50, issue: "12V first", summary: "Mach-E brick is often 12V, not the traction pack.", stop: "No READY plus HV: stop." , url: "https://www.ford.com" },
  { make: "Hyundai", make_slug: "hyundai", model: "Tucson", model_slug: "tucson", gen: "NX4", gen_slug: "nx4", variant: "1.6 T-GDi", variant_slug: "1-6-tgdi", years: Y(2021, 2025), engine: "1.6 turbo", engine_code: "G4FP", trans: "7-speed DCT", spec: "ACEA C2", visc: "0W-20", cap: 4.8, tyre: "235/55R19", pf: 2.4, pr: 2.4, bat: "AGM", ah: 70, issue: "NX4 is not TL", summary: "Do not copy a 2016 Tucson oil row.", stop: "Oil lamp: stop." , url: "https://www.hyundai.com" },
  { make: "Kia", make_slug: "kia", model: "Sportage", model_slug: "sportage", gen: "NQ5", gen_slug: "nq5", variant: "1.6 T-GDi", variant_slug: "1-6-tgdi", years: Y(2022, 2025), engine: "1.6 turbo", engine_code: "G4FP-S", trans: "7-speed DCT", spec: "ACEA C2", visc: "0W-20", cap: 4.8, tyre: "235/55R18", pf: 2.4, pr: 2.4, bat: "AGM", ah: 70, issue: "NQ5 is not QL", summary: "Sportage NQ5 oil and DCT notes differ from QL.", stop: "Oil lamp: stop." , url: "https://www.kia.com" },
  { make: "Peugeot", make_slug: "peugeot", model: "208", model_slug: "208", gen: "P21", gen_slug: "p21", variant: "1.2 PureTech", variant_slug: "1-2-puretech", years: Y(2019, 2025), engine: "1.2 turbo", engine_code: "EB2ADTD-208", trans: "6-speed", spec: "PSA B71 2312", visc: "0W-30", cap: 3.5, tyre: "195/55R16", pf: 2.3, pr: 2.1, bat: "EFB", ah: 50, issue: "Wet belt — official interval", summary: "208 PureTech wet-belt years are handbook items.", stop: "Knock plus oil pressure: stop." , url: "https://www.peugeot.com" },
  { make: "Peugeot", make_slug: "peugeot", model: "308", model_slug: "308", gen: "P51", gen_slug: "p51", variant: "1.2 PureTech", variant_slug: "1-2-puretech", years: Y(2021, 2025), engine: "1.2 turbo", engine_code: "EB2DTS-308", trans: "EAT8", spec: "PSA B71 2312", visc: "0W-30", cap: 3.5, tyre: "205/55R16", pf: 2.4, pr: 2.2, bat: "EFB", ah: 60, issue: "P51 is not T9", summary: "Do not copy a 2014 308 service schedule.", stop: "Oil lamp: stop." , url: "https://www.peugeot.com" },
  { make: "Renault", make_slug: "renault", model: "Clio", model_slug: "clio", gen: "V", gen_slug: "5", variant: "1.0 TCe", variant_slug: "1-0-tce", years: Y(2019, 2025), engine: "1.0 turbo", engine_code: "H4D-C", trans: "6-speed", spec: "RN17", visc: "5W-30", cap: 4.0, tyre: "185/65R15", pf: 2.3, pr: 2.1, bat: "EFB", ah: 50, issue: "Clio V is CMF-B", summary: "Older Clio IV oil notes do not apply.", stop: "Oil lamp: stop." , url: "https://www.renault.com" },
  { make: "Renault", make_slug: "renault", model: "Austral", model_slug: "austral", gen: "HFC", gen_slug: "hfc", variant: "1.2 E-Tech", variant_slug: "1-2-etech", years: Y(2022, 2025), engine: "1.2 hybrid", engine_code: "HR12", trans: "multimode", spec: "RN17 FE+", visc: "0W-20", cap: 4.4, tyre: "215/65R17", pf: 2.4, pr: 2.4, bat: "AGM", ah: 60, issue: "E-Tech 12V first", summary: "Austral hybrid READY faults are often 12V.", stop: "No READY: test 12V." , url: "https://www.renault.com" },
  { make: "Volvo", make_slug: "volvo", model: "EX30", model_slug: "ex30", gen: "SEA", gen_slug: "sea", variant: "Single Motor", variant_slug: "sm", years: Y(2024, 2026), engine: "electric", engine_code: "EX30-SM", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "245/45R19", pf: 2.6, pr: 2.6, bat: "12V Li-ion", ah: 8, issue: "12V lithium first", summary: "EX30 no-start is often 12V, not the traction pack.", stop: "No READY plus HV: stop." , url: "https://www.volvocars.com" },
  { make: "Skoda", make_slug: "skoda", model: "Enyaq", model_slug: "enyaq", gen: "E5", gen_slug: "e5", variant: "60", variant_slug: "60", years: Y(2021, 2025), engine: "electric", engine_code: "APP310-60", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "235/55R19", pf: 2.5, pr: 2.5, bat: "AGM", ah: 40, issue: "MEB 12V first", summary: "Enyaq brick is often 12V isolation.", stop: "No READY plus HV: stop." , url: "https://www.skoda-auto.com" },
  { make: "Nissan", make_slug: "nissan", model: "Qashqai", model_slug: "qashqai", gen: "J12", gen_slug: "j12", variant: "1.3 DIG-T", variant_slug: "1-3-digt", years: Y(2021, 2025), engine: "1.3 turbo", engine_code: "HR13DDT", trans: "Xtronic", spec: "Nissan / ACEA C3", visc: "5W-30", cap: 5.4, tyre: "215/65R17", pf: 2.3, pr: 2.3, bat: "EFB", ah: 60, issue: "J12 is not J11", summary: "Qashqai J12 1.3 is not the old 1.2 DIG-T row.", stop: "Oil lamp: stop." , url: "https://www.nissan-global.com" },
  { make: "Nissan", make_slug: "nissan", model: "Leaf", model_slug: "leaf", gen: "ZE1", gen_slug: "ze1", variant: "40 kWh", variant_slug: "40", years: Y(2018, 2024), engine: "electric", engine_code: "EM57-40", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "205/55R16", pf: 2.5, pr: 2.5, bat: "12V flooded", ah: 45, issue: "12V first on Leaf", summary: "A silent Leaf is often 12V, not the traction pack.", stop: "No READY plus HV: stop." , url: "https://www.nissan-global.com" },
  { make: "Mazda", make_slug: "mazda", model: "CX-30", model_slug: "cx-30", gen: "DM", gen_slug: "dm", variant: "2.0 Skyactiv-G", variant_slug: "2-0-skyactiv-g", years: Y(2019, 2025), engine: "2.0 petrol", engine_code: "PE-VPS-30", trans: "6-speed", spec: "Mazda / API SP", visc: "0W-20", cap: 4.2, tyre: "215/55R18", pf: 2.5, pr: 2.3, bat: "EFB", ah: 60, issue: "Skyactiv-X is a different row", summary: "This page is Skyactiv-G, not X.", stop: "Misfire plus catalyst lamp: stop." , url: "https://www.mazda.com" },
  { make: "Opel", make_slug: "opel", model: "Mokka", model_slug: "mokka", gen: "B", gen_slug: "b", variant: "1.2 Turbo", variant_slug: "1-2-turbo", years: Y(2021, 2025), engine: "1.2 turbo", engine_code: "EB2ADTD-M", trans: "8-speed auto", spec: "Opel / PSA B71 2312", visc: "0W-30", cap: 3.5, tyre: "215/60R17", pf: 2.4, pr: 2.2, bat: "EFB", ah: 50, issue: "Mokka B is PSA-based", summary: "Do not use a Mokka A 1.4 oil row.", stop: "Oil lamp: stop." , url: "https://www.opel.com" },
  { make: "Fiat", make_slug: "fiat", model: "500e", model_slug: "500e", gen: "332", gen_slug: "332", variant: "42 kWh", variant_slug: "42", years: Y(2020, 2025), engine: "electric", engine_code: "500E-42", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "185/55R15", pf: 2.4, pr: 2.4, bat: "AGM", ah: 40, issue: "12V first", summary: "500e brick is often 12V.", stop: "No READY plus HV: stop." , url: "https://www.fiat.com" },
  { make: "Mini", make_slug: "mini", model: "Countryman", model_slug: "countryman", gen: "F60", gen_slug: "f60", variant: "Cooper S", variant_slug: "cooper-s", years: Y(2017, 2023), engine: "2.0 petrol", engine_code: "B48A20A", trans: "8-speed auto", spec: "BMW Longlife-01 FE / 17 FE+", visc: "0W-20", cap: 5.3, tyre: "225/55R17", pf: 2.4, pr: 2.4, bat: "AGM", ah: 80, issue: "B48 oil is FE", summary: "F60 Cooper S is not an R60 Prince copy.", stop: "Oil lamp: stop." , url: "https://www.mini.com" },
  { make: "Tesla", make_slug: "tesla", model: "Model 3", model_slug: "model-3", gen: "Highland", gen_slug: "highland-lr", variant: "Long Range AWD", variant_slug: "lr-awd", years: Y(2023, 2026), engine: "electric", engine_code: "M3-LR-H", trans: "1-speed", spec: "None (EV)", visc: "n/a", cap: 0, tyre: "235/45R18", pf: 2.9, pr: 2.9, bat: "12V Li-ion", ah: 6, issue: "Door-sticker pressures only", summary: "AWD load changes PSI. We do not invent a winter figure.", stop: "TPMS plus vibration: inspect." , url: "https://www.tesla.com" },
  { make: "Hyundai", make_slug: "hyundai", model: "Kona", model_slug: "kona", gen: "OS", gen_slug: "os", variant: "1.0 T-GDi", variant_slug: "1-0-tgdi", years: Y(2017, 2023), engine: "1.0 turbo", engine_code: "G3LC-K", trans: "6-speed", spec: "ACEA C2", visc: "0W-20", cap: 3.6, tyre: "205/60R16", pf: 2.3, pr: 2.1, bat: "EFB", ah: 60, issue: "Kona OS is not SX2", summary: "Do not copy a 2024 Kona oil row onto OS.", stop: "Oil lamp: stop." , url: "https://www.hyundai.com" },
];

export const SCALE_VEHICLES: VehicleIdentity[] = SEEDS.map(vehicle);
